### ISSUE TITLE
[Bug] updateElement on customElement doesn't apply changes in React

### ISSUE THREAD

**Issue by cHasee002** [PDFTron/webviewer-ui#1004]
**WebViewer version**
8.7.1

**The current behavior**

I am trying to update the title of a customElement but it doesn't seem to be working at all and no error message is shown.

The code for updating the element:

```
 UI.updateElement("customButton", {
    title: generateTooltipText(...),
  });
```

The custom element is added to the textPopupp like this:

```
UI.textPopup.update([
  {
    className: "CustomElement Button",
    type: "customElement",
    dataElement: "customButton",
    title: "Summarization",
    render: () => <PopupButton />,
  },
]}
```

**The expected behavior**

The title of the customElement should change when the updateElement method is called.

**Steps to reproduce**

Add a customElement to the textPopup like in the code above and update only the title of the element.

**Comment by bollain** [comment]
Hey @cHasee002,

I'm able to reproduce this issue. I have added it to our backlog. At this time I cant provide an estimate on when it will be worked on, but once it gets scheduled in a sprint we will provide you with an update.

**Comment by bollain** [comment]
Hi @cHasee002, 

We have reviewed this issue, and this is actually expected. The [updateElement](https://docs.apryse.com/api/web/UI.html#.updateElement) API is only designed to work with Buttons, not custom elements, such as your slider. 

if you need to dynamically change the property of custom elements, you can simply call `UI.textPopup.update..`with your updated element. If you are adding custom buttons, the API will work, just make sure you cadd the correct type such as `actionButton` (More button types [here](https://docs.apryse.com/documentation/web/guides/customizing-header/#actionbutton)).
