### ISSUE TITLE
[Bug] ViewMode `FitPage` not respected on Android devices

### ISSUE THREAD

**Issue by angelaki** [PDFTron/webviewer-ui#1012]
**Version 8.12.0**

Currently, the method `instance.UI.setFitMode(instance.UI.FitMode.FitPage)` somehow doesn't seam to work for Android devices. The document is just shown zoomed. It even works with Chrome Dev Tools, emulation e.g. a _Samsung Galaxy S8+_. If I switch to _iPhone SE_ it works as expected.

Just load a large, horizontal PDF to check.

**Comment by bollain** [comment]
Hi Angela, this would be better tracked as a bug report in our support channel as it appears to be an issue with the WebViewer core, and not specific to the UI. Please submit this via our support channel and include all relevant info and any documents where this happens:
https://support.apryse.com/support/tickets/new
