### ISSUE TITLE
Is there a way to render only certain pages of the document?

### ISSUE THREAD

**Issue by evansavage** [PDFTron/webviewer-ui#1013]
Hello!

I am trying to build a feature for a document viewer that is displaying one large PDF of smaller concatenated PDF documents in React. When the user drags a thumbnail, I would like to only display the thumbnails of the pages in the same underlying document. For example, let's say the total PDF pages are 24, comprised of 3 underlying PDF documents:

- Doc 1: 13 pages [1-13]
- Doc 2: 5 pages [14-18]
- Doc 3: 6 pages [19-24]

If the user clicks on page 15, I would only like to show the thumbnails for pages 14-18, so that page reordering can only happen respectively to the underlying document. I know the order and how many pages are in each underlying document outside of pdftron. Is there any way to configure this?

**Comment by bollain** [comment]
Hi @evansavage,

I think this is feasible, but may be tricky to implement. First of all, is this just a document that was merged together into a single one, or is it something like a PDF portfolio? 

In any case, I think you would need to modify the [ThumbnailsPanel](https://github.com/PDFTron/webviewer-ui/blob/10.0/src/components/ThumbnailsPanel/ThumbnailsPanel.js) to only render a subset of thumbnail pages - and it will be up to you to determine what that entails (i.e. how will you differentiate a sub-document inside the document?). If you limit which thumbnails are render, then you also achieve your requirement of only allowing re-ordering/manipulating within that subset. 

But as noted above, this is not something that is configurable, you would need to fork this repo and implement the logic for rendering the specific thumbnails. 

Perhaps the easier approach would be to split your original PDF into separate parts, and then only load the part you want to edit into the viewer. Once the user is done editing/manipulating this part, you can merge it back into the original document. 
You can explore the available APIs:
- [extractPages](https://docs.apryse.com/api/web/Core.Document.html#extractPages)
- [insertPages](https://docs.apryse.com/api/web/Core.Document.html#insertPages__anchor)

If you have any further questions feel free to reach out through our [support](https://apryse.com/support) portal.
