### ISSUE TITLE
[Bug] Some of french translation are incorrect or inaccurate.

### ISSUE THREAD

**Issue by leolade** [PDFTron/webviewer-ui#1015]
**WebViewer version**
10.0.1

**Some context**
I work for a french company which sell a product with PDFTron web viewer inside. All of our customers are french native speakers.
I'm also a french native speaker working with french business analyst. 
We have several feedbacks and dissatisfactions with the quality of translation. 

**The current behavior**
Some of french translation are incorrect or inaccurate. 
There is all mistranslation we noticed

1. "outlinePanel": "Présenter", -> The word "[Présenter](https://www.larousse.fr/dictionnaires/francais/pr%C3%A9senter/63700)" doesn't fit the context here
1. "outlinesPanel": "Contours", -> The word "[Contours](https://www.larousse.fr/dictionnaires/francais/contour/18634)" doesn't fit the context here
1. "specifyPages": "Spécifiez les pages", -> The verb "Spécifiez" is not at the right verbal tense
1. "unmarked": "Mon marqué" -> The word "[Mon](https://www.larousse.fr/dictionnaires/francais/mon/52143)" has a spelling mistake (here we want to translate"not" probably with "non")
1. "fontStyle": "Font style", -> Not translate here, in french we say "[Police d'écriture](https://www.google.com/search?q=police+d%27%C3%A9criture)"
1. "second": "Deuxième", -> Lack of context here, "Deuxième" is the french translation of "Second of a race" for example. 
1. "specify": "Spécifier les pages", -> The verb "Spécifiez" is not at the right verbal tense
1. "selectMessage": "Veuillez sélectionner des pages et réessayer." -> The verb "réessayer" is not at the right verbal tense
1. "fieldName": "Nom de domaine", -> The word "[Domaine](https://www.larousse.fr/dictionnaires/francais/domaine/26352)" is not understable in this context
1. "readOnly": "Lecture seulement", -> This is litteral traduction but on the french web we say "Lecture seule"
1. "flags": "Drapeaux de terrain", -> The expression doesn't exist in french 
1. "noSignatureFields": "Ce document n'a pas de champs de signature",  -> The word "champs" is plural here for no reason.
1. "applyTitle": "Appliquer la culture ?", -> The word "[culture](https://www.larousse.fr/dictionnaires/francais/culture/21072)" is not understable in this context
1. "applyMessage": "Cette action recadrera de manière permanente toutes les pages sélectionnées sélectionnées. Ça ne peut pas être défait.", -> The word "sélectionnées" is in double
      

**The expected behavior**
1. "outlinePanel": "Présenter", -> Replace by "[Élément](https://www.larousse.fr/dictionnaires/francais/%C3%A9l%C3%A9ment/28372)", it's a little bit generic, by more understable.
1. "outlinesPanel": "Contours", -> Replace by "[Plan](https://www.larousse.fr/dictionnaires/francais/plan/61347)"
1. "specifyPages": "Spécifiez les pages", -> Replace by "Spécifier" (indicatif verbal tense)
1. "unmarked": "Mon marqué" -> Replace by "non"
1. "fontStyle": "Font style", -> Replace by "Police" because "Police d'écriture" is redundant here
1. "second": "Deuxième", -> replace by "[seconde](https://www.larousse.fr/dictionnaires/francais/second/71726#70933)" which is the correct word when you speak of time
1. "specify": "Spécifiez les pages", -> Replace by "Spécifier" (indicatif verbal tense)
1. "selectMessage": "Veuillez sélectionner des pages et réessayer." -> Replace by "Spécifiez" (impératif verbal tense)
1. "fieldName": "Nom de domaine", -> Replace by "[champ](https://www.larousse.fr/dictionnaires/francais/champ/14557)" which is the translation of "Field" on web context.
1. "readOnly": "Lecture seulement", -> Replace by "Lecture seule"
1. "flags": "Drapeaux de terrain", -> Replace by "[Caractéristiques](https://www.larousse.fr/dictionnaires/francais/caract%C3%A9ristique/13065)"
1. "noSignatureFields": "Ce document n'a pas de champs de signature",  -> Replace by singular "champ"
1. "applyTitle": "Appliquer la culture ?", -> Replace by "Appliquer la recadrage" like in `"applyTitle": "Appliquer le recadrage ?",`
1. "applyMessage": "Cette action recadrera de manière permanente toutes les pages sélectionnées sélectionnées. Ça ne peut pas être défait.", -> remove on of "sélectionnées"

**Steps to reproduce**
1. Use webviewer in French
2. Navigate in many menus.

**Comment by bollain** [comment]
Thanks for bringing this up to our attention - your PR has now been merged.
