### ISSUE TITLE
[Feature Request] Thumbnail Panel supports increasing displayed number of thumbnails 

### ISSUE THREAD

**Issue by calebfagan-vu** [PDFTron/webviewer-ui#1022]
**Is your feature request related to a problem? Please describe.**
When expanding the thumbnail panel in the WebViewer, the number of thumbnails is capped at 3 columns. Which leads to a LOT of wasted space and slows our users down a lot. 

**Describe the solution you'd like**
We would like a way to increase the maximum number of thumbnails shown in the thumbnail panel by removing or customizing the cap of 3 columns.

We would also love a way to programmatically increase the width of the thumbnail panel so that we may load the viewer with the thumbnail panel already expanded.
 
**Why is this feature important to your users?**
Our users need to very quickly split these documents into many different individual documents. Speed is important because the users are measured on their ability to do this process. Today they use the thumbnails to recognize the document pages and in a different tool and can do it in < 3min.

**Desired timeline**
We have reached out to Apryse support about this issue and the timeline did not work out. We are interested in following the contribution guide to issue a pull request and are creating this issue as a part of that.

**Comment by bollain** [comment]
Hey @calebfagan-vu,

Thanks for submitting this request. We have triaged the request you submitted for this feature via our support channel and the work has been scheduled in an upcoming sprint in July. This feature will be available in our next release (10.3). I will keep this issue open until it has been finalized, but feel free to reach out via the existing support ticket to get further updates.

**Comment by bollain** [comment]
Hey @MasonAshlock,

Glad to hear the update worked for you! For your latest question, that would be the way to do it. We don't currently expose that API, but if you forked the UI that is the best way to acheive this.

**Comment by bollain** [comment]
I'll set this as closed but don't hesitate to re-open if you have any other questions.
