### ISSUE TITLE
Documents are not displaying on production. logging undefined to console. PDFworker.js: 48

### ISSUE THREAD

**Issue by anistanyoganath** [PDFTron/webviewer-ui#1023]
**WebViewer version**
"10.2.0"
**The current behavior**
The document is not displaying in the production
I can see a message in the console that, says "undefined"  PDFworker.js: 48
 but in the localhost, It works.
**The expected behavior**

**Steps to reproduce**
installed package using npm

integrated according to the documentation
 WebViewer(
            {
                path: "/pdftron/",
                licenseKey: pdftronLicenseKey,
                disabledElements: ["header", "toolsHeader"],
                fullAPI: true
            },
            viewerRef?.current!
        ).then(instance => {
            instance.UI.loadDocument(props.document);
        });

Added pdftron public files from node_modules to build/public of react project

**Comment by bollain** [comment]
Hi @anistanyoganath,

If you only see this issue in production, it is likely an issue with MIME types. We have a guide about this [here](https://docs.apryse.com/documentation/web/faq/mime-types/).

If this does not resolve the issue for you, please submit a ticket directly to our support team [here](https://support.apryse.com/support/tickets/new).
