### ISSUE TITLE
[Bug] Inconsistent translations of "comments" into german

### ISSUE THREAD

**Issue by vekunz** [PDFTron/webviewer-ui#1024]
**WebViewer version**

10.2.3

**The current behavior**

"Comments" are sometimes translated to "Kommentare" and sometimes to "Notizen" (which means 'notes'). This is confusing for the customers.

**The expected behavior**

Comments should be called the same everywhere.

I can create a Pull Request for this if you want (actually I wanted to create a Pull Request in the first place, but I was a bit confused about which branch the PR should be based on).

**Comment by bollain** [comment]
Hi @vekunz,

Thanks for reaching out with this report. We fixed a number of German transaltions for 10.3 - you can find the latest here:
https://github.com/PDFTron/webviewer-ui/blob/10.3/i18n/translation-de.json

If there are still deficiencies, we will gladly review a PR to update them. You can make a PR to our master branch. When we merge it, I will then internally synch up master with the release branch, which will also ensure the translations go out in our nightly builds.

Let me know if you have any questions about this.

**Comment by vekunz** [comment]
Hi, after reviewing the English translation again, I am a bit confused myself. The inconsistency between "comments" and "notes" also exists in the English translation. The same thing is sometimes called "comment" and sometimes "notes" (even in the same view). So basically the German translation accurately reflects the English translation, but even the English translation is confusing.

**Comment by bollain** [comment]
Hi @vekunz, perhaps the confusion is between a sticky note annotation and a comment? Comments can be added to all annotations. Sticky notes, while also considered comments, are their own type of annotation. These are the terms defined in the PDF spec, but we do have APIs in place if you want to override any translations withotut having to fork this repo or change the translations file. 
https://docs.apryse.com/api/web/UI.html#.setTranslations

If you think there are other deficiencies in our German translations, we'll review your PR.
