### ISSUE TITLE
[Bug] When shift clicking to multiselect, selects more than expected

### ISSUE THREAD

**Issue by MasonAshlock** [PDFTron/webviewer-ui#1026]
**WebViewer version**
10.3
**The current behavior**
When shift clicking multiple thumbnails, then attempting to shift click more, the Shift Key Pivot Index is at the wrong point. This results in an odd user experience.
https://www.loom.com/share/276b9b24c711422b92e57d70260300c9?sid=88870f22-d229-4083-8404-288afd3e6432
**The expected behavior**
Shift clicking a thumbnail always selects the thumbnails between the last selected and shift-clicked thumbnail and not having to use the control key to change the pivot point.
**Steps to reproduce**
Click thumbnail 1, then shift-click thumbnail 3. Uncheck all thumbnails(not required). Click thumbnail 4, then shift-click thumbnail 7. Notice thumbnails 1 through 7 are checked. 

[the code](https://github.com/PDFTron/webviewer-ui/blob/1daf3410f053d55b0dd5ff5213e33748bcc6f087/src/components/Thumbnail/Thumbnail.js#L172C17-L172C17)

**Comment by bollain** [comment]
Hey @MasonAshlock,

Thanks for this report. I have added this to our backlog, when it gets fixed we'll let you know via this issue so you can get the latest version.

**Comment by bollain** [comment]
Hi @MasonAshlock, 

This bug has been fixed and will be part of our 10.5 release due next week.
