### ISSUE TITLE
[Question] Where to add license Key? 

### ISSUE THREAD

**Issue by exotexot** [PDFTron/webviewer-ui#1027]
When developing on the webviewer-ui, I get this message.
I have a valid key, but I don't know where to add it, in order to get rid of this warning..

![Screenshot 2023-08-20 at 12 00 50](https://github.com/PDFTron/webviewer-ui/assets/10153413/d7605ddd-5a3e-4d6e-9406-fae29209b0b5)

**Comment by mparizeau-pdftron** [comment]
Here is how you can pass your license key into the WebViewer constructor https://docs.apryse.com/documentation/web/faq/add-license/#passing-into-constructor

**Comment by rstar2** [comment]
What about when working in this ` webviewer-ui` project itself, e.g. when starting dev server with `npm start`, there's no WebViewer constructor used here, or am I missing.
