### ISSUE TITLE
[Bug] If SearchPanel sits within LeftPanel, than after Search is executed width of viewport becomes smaller.

### ISSUE THREAD

**Issue by exotexot** [PDFTron/webviewer-ui#1028]
**WebViewer version**
10.3.0

**The current behavior**
After hitting executing the search, a void appears on the RIGHT side of the document, effectively shrinking the width of the "viewport". This also doesn't restore after closing the search.  I guess this is somehow related to the original position being on the right side of Document.

**The expected behavior**
Executing of search does NOT limit the width of the view power 

**Steps to reproduce**
I packed the SearchPanel inside the LeftPanel component.

https://github.com/PDFTron/webviewer-ui/assets/10153413/ad39ef23-e8ed-4dd4-8c2d-7c98cb80c367

**Comment by bollain** [comment]
Hi @exotexot.

In its current state, the search panel is only designed to be in the right panel. If you are customizing the viewer to move the panel to the left you will need to change the code that removes the dependencies of having the search panel on the right side. 

We are currently working on a more customizable approach to the viewer that will allow panels to be placed on the left or right without requiring you to fork this repo, but this is not due for completion until the end of the year. If you are looking for a quicker solution, you would need to change your custom UI to not resize the viewer on the right side. You can start by modifying the [DocumentContainer](https://github.com/PDFTron/webviewer-ui/blob/10.3/src/components/DocumentContainer/DocumentContainer.js#L33).

**Comment by exotexot** [comment]
Hi @bollain 

Thanks for pointing me in the right direction! 
Removing Line 109 solved the issue for me!

**Comment by bollain** [comment]
Glad to hear that helped - stay tuned for our new APIs that will allow lots of customization options without having to fork this repo!
