### ISSUE TITLE
[Feature Request] More customizable print modal

### ISSUE THREAD

**Issue by sabieber** [PDFTron/webviewer-ui#1031]
**Preample**

We run a highly customized instance of the WebViewer to provide our customers a tailored experience. Most of this can be done by providing a JS config file, but some customizations we need require us to maintain a fork of the webviewer-ui. This increases the time and effort each version upgrade takes. Because of this we would like to suggest some expansions / APIs.

Also we think other users of the webviewer-ui could also benefit from this suggestion.

**Is your feature request related to a problem? Please describe.**

We hide some of the options in the print modal and add autofocus to the pages input field.
Most of them can be hidden via the `dataElement` attribute and the `instance.UI.disableElements` function, but one cant.

**Describe the solution you'd like**

* Either by default (if deemed useful) or as an option allow the pages input field to gain autofocus.
* Allow to hide the print quality selection via `instance.UI.disableElements`
 
**Why is this feature important to your users?**

The print modal has quite a few options that are not relevant to our users so they want a more streamlined process.

**Desired timeline**

Next version would be ideal so we can reduce the amount of fork updates we have to do.

**Comment by sabieber** [comment]
Here is our current implementation for this: https://github.com/sabieber/webviewer-ui/commit/4bad4200a9786b588f3a66d943c48a4b8fb370be

**Comment by bollain** [comment]
Hey @sabieber,

Thanks for this feedback. 

We do have an API to create a custom modal, if you wish to completely replace the print modal without having to fork this repo:
[addCustomModal](https://docs.apryse.com/api/web/UI.html#.addCustomModal)
[printInBackground](https://docs.apryse.com/api/web/UI.html#.printInBackground__anchor)

You would then need to rewire the hotkeys etc to open your modal as well as disabling the existing modal, but it would give you full control of the modal code without the extra work of keeping this fork up to date. 

For the issue of not being able to disable the Page Quality, that seems like a bug to me and I will add an item to our backlog to ensure everything in this modal has data elements so they can be disabled. I'll update this ticket when this gets addressed.

**Comment by blaine-albert-apryse** [comment]
Hello @sabieber,

We have an update for you.

The print quality section of the print modal will have a data-element in our 10.5 release.

You may target it using `instance.UI.disableElements(['printQuality'])`.

The related commit may be found [here](https://github.com/PDFTron/webviewer-ui/commit/461d02b6183d59080442225e1c79db344101b688).
