### ISSUE TITLE
[Feature Request] API for rendering custom header section in notes panel

### ISSUE THREAD

**Issue by sabieber** [PDFTron/webviewer-ui#1032]
**Preample**

We run a highly customized instance of the WebViewer to provide our customers a tailored experience. Most of this can be done by providing a JS config file, but some customizations we need require us to maintain a fork of the webviewer-ui. This increases the time and effort each version upgrade takes. Because of this we would like to suggest some expansions / APIs.

Also we think other users of the webviewer-ui could also benefit from this suggestion.

**Is your feature request related to a problem? Please describe.**

We allow our customers to invoke some (like downloading it) actions on each page in the thumbnail panel. For this we need to be able to render custom elements next to each thumbnail in the sidebar.

**Describe the solution you'd like**

For this we expanded the Thumbnail class with a custom API that allows us to simply render some content next to the page label. Here is our current implementation for it: https://github.com/sabieber/webviewer-ui/commit/69c22b59fdd3a1d2d3ea91dfc09cfd14bdf9bd88

![image](https://github.com/PDFTron/webviewer-ui/assets/2427877/cdfdba0d-dadb-4f33-b4a9-b4826583a083)

This could also allow other WebViewer users to display other information or actions for each page.
 
**Why is this feature important to your users?**

The options we provide here are crucial to our users and happen in the context of a page, so the most intuitive place for them is within the thumbnails panel.

**Desired timeline**

Next version would be ideal so we can reduce the amount of fork updates we have to do.

**Comment by bollain** [comment]
Hi @sabieber,

We have two existing APIs that allow you to customize this. 

- The [ThumbnailControlMenu](https://docs.apryse.com/api/web/UI.ThumbnailControlMenu.html#main) API allows you to set custom items to be rendered in that spot:
![image](https://github.com/PDFTron/webviewer-ui/assets/10825527/40dce062-b363-4ab8-ae2a-08016274f631)

- The [PageManipulationOverlay](https://docs.apryse.com/api/web/UI.PageManipulationOverlay.html#main) API, which allows you to customize the options that are shown in this menu.
![image](https://github.com/PDFTron/webviewer-ui/assets/10825527/8caaa096-6d83-4fbf-b06d-887c47e641e6)

Both of these APIs should allow you to achieve what you want without havign to fork this repo.
