### ISSUE TITLE
[Bug] Preview file: Cannot read properties of undefined (reading 'Annotations') version 10.4.0

### ISSUE THREAD

**Issue by phuchoangd** [PDFTron/webviewer-ui#1033]
**WebViewer version**
@pdftron/webviewer: 10.4.0

**The current behavior**
I preview file (pdf, docx,...) in my web application (Angular 13) use [WebViewer.WebComponent()](https://docs.apryse.com/documentation/web/guides/web-component-vs-iframe/#webviewer-as-a-web-component) but **sometime** file cannot preview and show Error: _Cannot read properties of undefined (reading 'Annotations')_

![image](https://github.com/PDFTron/webviewer-ui/assets/13614341/c64a84f0-a60c-4364-86f9-b8aa3d08c2bb)

getMeasurementTools.js:3  Uncaught TypeError: Cannot read properties of undefined (reading 'Annotations')
    at Object.<anonymous> (getMeasurementTools.js:3:42)
    at o (bootstrap:63:22)
    at Object.<anonymous> (webviewer-ui.min.js:22:74798)
    at o (bootstrap:63:22)
    at Module.<anonymous> (webviewer-ui.min.js:75:325168)
    at o (bootstrap:63:22)
    at bootstrap:198:10
    at webviewer-ui.min.js:1:2096
(anonymous) @ getMeasurementTools.js:3
o @ bootstrap:63
(anonymous) @ webviewer-ui.min.js:22
o @ bootstrap:63
(anonymous) @ webviewer-ui.min.js:75
o @ bootstrap:63
(anonymous) @ bootstrap:198
(anonymous) @ webviewer-ui.min.js:1

_**Note**_: _I have investigated and determined that maybe because webviewer-core.min.js loads slower than webviewer-ui.min.js, it gives an error and cannot re-render the WebViewer component **from the second time onwards (Reference at Step 4)**._

**The expected behavior**
I would like preview file always work fine.

**Steps to reproduce**

Step 1: access to "Files" site
Step 2: preview ".PDF" file (preview file success)
Step 3: go to another page
Step 4: back to "Files" site
Step 5: preview ".PDF" file (preview file Error, message: "Cannot read properties of undefined (reading 'Annotations')")

Example: preview file has error on Web application (Angular 13)
![image](https://github.com/PDFTron/webviewer-ui/assets/13614341/4a9d5ebc-8b75-49b8-8244-35166ef3f476)

**Comment by bollain** [comment]
Hi @phuchoangd,

As this is an issue that potentially involves WebViewer Core, it is best addressed via our support system. Please submit a ticket with all relevant info and repro steps here:
https://support.apryse.com/support/tickets/new

Thanks
