### ISSUE TITLE
[Feature Request] Custom Right Click Menu for Bookmarks

### ISSUE THREAD

**Issue by sabieber** [PDFTron/webviewer-ui#1035]
**Is your feature request related to a problem? Please describe.**

We would like to offer users some options when they right-click on bookmark entries in the table of contents. These include printing the range of pages a bookmark "encapsulates" (the page of the bookmark until the next bookmark on the same level starts) or passing that range to some other functionality.

Example use case:

TOC of document:

- English (1)
  - Chapter 1 (1)
  - Chapter 2 (12)
  - Chapter 3 (19)
- German (25)
  - Chapter 1 (25)
  - Chapter 2 (36)
  - Chapter 3 (43)

User right clicks the english bookmark and selects print -> print modals opens with the range to print pre-filled with 1 - 24 (clickedChapter & nextChapter - 1)

**Describe the solution you'd like**

Two ways this could be implemented:

1) An event thats triggered when a user right clicks a bookmark. This could then be used to call the new way of creating and positioning a popup mentioned [here](https://github.com/PDFTron/webviewer-ui/issues/34#issuecomment-1773461342) to display a popup with the desired options. When an option is clicked the bookmark-range could be calculated by us and passed to the print modal or other functions.

2) A custom API that allows to provide popup options for the right click menu of bookmarks that gets passed the calculated bookmark range when clicked.
 
**Why is this feature important to your users?**

Its a highly requested feature by some of our customers that use the table of contents quite extensively, e. g. when combining multiple languages into one document.
Also they miss this feature from working with Adobe Acrobat on their desktop, where this is possible.

**Comment by bollain** [comment]
Hi @sabieber,

Apologies for the delayed response on this one. We added this feature to our backlog - I have chatted with my colleague who got your ticket via freshdesk and we synched up on this one. In terms of feasibility this is definitely doable. 

I will close this issue; you will receive updates via freshdesk on the status of this as it makes its way through our dev cycle. Apologies again for the delay, and don't hesitate to reach out if you have any other ideas or issues. 

Happy holidays
