### ISSUE TITLE
Fit Mode doesnt work for the second document 

### ISSUE THREAD

**Issue by pallaviMN** [PDFTron/webviewer-ui#1039]
instance.UI.setMaxZoomLevel(1.5)
  instance.UI.enableFeatures([instance.UI.Feature.MultiViewerMode]);
 documentViewer2.addEventListener('documentLoaded', () => {
 instance.UI.setFitMode(FitMode.FitWidth);
 })
 
 This above code only solve for the first document, but not for the second one

**Comment by bollain** [comment]
Hi @pallaviMN,

Thanks for reaching out. Please submit this via our support page, where it will be triaged properly:
https://apryse.com/form/request

Please include all relevant code to repro the issue, including sample documents if this only happens with a specific set of documents. 

Thanks
