### ISSUE TITLE
PDF with 3d Data shows black page

### ISSUE THREAD

**Issue by HarisRafiq** [PDFTron/webviewer-ui#1051]
**WebViewer version**
10.7
**The current behavior**
When you open any pdf containing 3d Data, it shows black page.
**The expected behavior**
It would be best to get a callback returning such information when the document loads so that we could show a dialog to the user telling them that we do not support such pdf instead of just showing black page
**Steps to reproduce**
Load any PDF with 3d data in [it](url)
![image](https://github.com/PDFTron/webviewer-ui/assets/11950271/b28cd836-4945-433e-be75-ab7bbee20f8d)

**Comment by bollain** [comment]
Hi @HarisRafiq, 

You can submit this as a feature request via our support channel:
https://apryse.com/form/request
