### ISSUE TITLE
Running latest version project changes throws multiple scss errors 

### ISSUE THREAD

**Issue by gramirezceg** [PDFTron/webviewer-ui#1058]
**WebViewer version:**
10.9

**The current behavior:**
The webviewer-ui project fails to run throwing multiple scss missing variable errors.

**The expected behavior:**
Project should load webviewer development environment when running `npm start` script.

**Steps to reproduce:**

- Run `npm install`
- Run `npm run download-webviewer`
- Run `npm start`

The browser auto launches, but multiple errors are shown when the site loads.

![image](https://github.com/PDFTron/webviewer-ui/assets/132108297/71e240bb-7bb5-4b16-b212-027e6d303ab8)
![image](https://github.com/PDFTron/webviewer-ui/assets/132108297/a1703557-828e-4466-82bd-3996a5584426)

**Comment by bollain** [comment]
Hi @gramirezceg, 

Thanks for this report! When the release for 10.9 was cut, several files were missed. I have made a PR to update the branch and have double checked it runs. Please pull the latest changes and let me know if you have any issues.

**Comment by gramirezceg** [comment]
Hi @bollain,

Can confirm it works now as expected. Thank you!
