### ISSUE TITLE
[Bug] Unable to open context menu

### ISSUE THREAD

**Issue by jacksontong** [PDFTron/webviewer-ui#1071]
**WebViewer version** 10.10.1

**The current behavior**
![image](https://github.com/PDFTron/webviewer-ui/assets/7871218/63df9a0a-0f43-47ce-9717-d4c93c8533fa)

As you can see from the screenshot, I have 2 tabs, the `pdf` tab is hidden by default, I notice that the context menu (right click) is not opening, but if I update `pdf` tab to be open by default then it would work.

**Steps to reproduce**

Example code https://github.com/jacksontong/apryse-webviewer-context-menu-bug/blob/main/src/App.tsx#L6

**Comment by bollain** [comment]
Hey @jacksontong - thanks for reaching out. This one seems like a better fit for our regular support channels:
https://apryse.com/form/request

Please include all relevant info - your sample repo should suffice.
