### ISSUE TITLE
Loader is jittery in IE/Edge

### ISSUE THREAD

**Issue by henry-chris** [PDFTron/webviewer-ui#115]
Looks like IE and (to a smaller degree) Edge cannot render a perfect circle through animations.  If you hold the loader up for very long in IE you can really tell that there is a lot of jitter.  

We have tried to implement some ad-hoc buttons and header items that display loaders until the information is ready.  Trying to keep with the same style, we used the CSS for your loader (so the problem crops up more often for us).  This is something that could definitely be fixed on our end, but I thought it might be something you might want to change, also.  We'd like to keep with your style whenever possible.

Here's the best SO post I found:
https://stackoverflow.com/questions/34597433/css-rotation-in-ie-is-jittery

**Comment by justinjung04** [comment]
Thank you for the heads up!
Actually from UI v1.1 (WebViewer 4.1) the spinner has been replaced to a progress bar, so I think that jittery issue should be gone.

**Comment by henry-chris** [comment]
Ahh ok.  I saw the new progress modal but we load in internal to the application instead of through the webviewer object.  I'll check out the progress modal and probably implement a different animation for our other loaders then.  Thanks.
