### ISSUE TITLE
It's buggy at "Layout Cover" to "Fit to Width"

### ISSUE THREAD

**Issue by mokalook** [PDFTron/webviewer-ui#122]
When I load the XOD file with webviewer, switch the layout to "Cover" mode, then click "Fit to Width" , I got an error: Uncaught Error: Page index is not loaded NaN

**Comment by justinjung04** [comment]
We have identified the issue, and add a fix to the latest WebViewer package: https://www.pdftron.com/downloads/WebViewer.zip
Please let me know how this works for you, and if you have any further questions.

**Comment by mokalook** [comment]
This fixed the issue. Thank you for your assistance.
