### ISSUE TITLE
Possible issue in 4.1 related to cover view and double page view

### ISSUE THREAD

**Issue by ascherer1993** [PDFTron/webviewer-ui#137]
In our project when we select continuous scroll, and then select either double page or the cover view, zooming (ctrl + scroll) causes a javascript error in corecontrols. It is possible it is something on our side, but I am not sure of what changes we have made that would even affect that. Attached is an image of the error.

![image](https://user-images.githubusercontent.com/18369440/51413204-b6765080-1b33-11e9-9fbb-d735182ce59f.png)

**Comment by ZhijieZhang** [comment]
Close this issue for now. Please reopen it if this issue is still happening. 
Thanks!
