### ISSUE TITLE
Allow mobile swipe in both horizontal and vertical direction for page turning?

### ISSUE THREAD

**Issue by sabieber** [PDFTron/webviewer-ui#141]
Recently we switched from "Continuous" to "Single" viewing mode as it provides far better performance when viewing huge documents.

On desktop this still allows for switching between pages wie "scrolling" the mouse wheel which is the same as when viewing documents in continuous mode.
On mobile on the contrary the user can no longer turn pages by swiping up/down but only left/right. This differs from the way the user interacted with the document before.

Would it be possible for you to add an option (or general functionality) to the webviewer ui to allow the user to swipe both vertically and horizontally to turn the pages of the document?

**Comment by JSpark22** [comment]
Hi Sascha,

Thanks for the request and sorry for the late response!  
setSwipeOrientation API has now been implemented which enables swiping horizontally, vertically, or in both directions. 
See the below image for reference. 
<img width="893" alt="setswipeorientation documentation" src="https://user-images.githubusercontent.com/42555515/52002016-b6504c00-2475-11e9-9b3a-b2ea08c11222.png">

Cheers!

**Comment by sabieber** [comment]
Thanks for implementing the API so quickly! Will test it but already looks perfekt.
