### ISSUE TITLE
Thumbnail and outline not matching after removing page

### ISSUE THREAD

**Issue by awy3** [PDFTron/webviewer-ui#144]
When we remove a page from the document, the thumbnail and outline on the left doesn't match up

Thumbnail after removing page:
![image](https://user-images.githubusercontent.com/45575633/51572640-f9e5fd00-1e5a-11e9-9d26-8c1f2dc3b2a7.png)

Outline after removing page:
![image](https://user-images.githubusercontent.com/45575633/51572694-331e6d00-1e5b-11e9-86d8-062682c55400.png)

Code ran:
` readerControl.docViewer.getDocument().removePages([1])`

**Comment by ZhijieZhang** [comment]
Discussed internally and we agreed that this issue has low priority, so I'm going to close it for now.
