### ISSUE TITLE
Page up and page down keys can't be intercepted

### ISSUE THREAD

**Issue by glendaviesnzdiligent** [PDFTron/webviewer-ui#162]
With legacy ui we used to listen the the page up and page down keys ourselves so we could use these to scroll the pdf up and down when it was zoomed in - and move forward or back if scrolled all way to top or bottom. 

In the new ui these keys are being trapped and propagation stopped so we can no longer intercept these key actions. Is it possible that the stop of propagation for these events can be removed?

**Comment by ZhijieZhang** [comment]
Hi,

The new UI listens to the `page up` and `page down` keys and will set the page number accordingly when they are pressed. 

 > these keys are being trapped and propagation stopped so we can no longer intercept these key actions.

If you open `onKeyDown.js`, you will see that between line 70-79 is where we handle those two keys and I don't think we are stopping propagation there.


Here is what I tried to intercept those key actions:
1. In the WebViewer download package, open viewing.js
2. Add following code snippet in the `ready` event
```javascript
var iframeDocument = viewerElement.querySelector('iframe').contentDocument;
iframeDocument.addEventListener('keydown', function(e) {
  if (e.key === 'PageUp' || e.which === 33) {
    console.log('PageUp key down');
  }
})
```
3. 'PageUp key down' will be printed in the console when I press the page up key

Can you try the above code and see if it works for you. Also, just to clarify, were you thinking about modify or remove how the UI is handling page up and page down keys by default?

**Comment by glendaviesnzdiligent** [comment]
Sorry, I was getting myself confused here - the issue wasn't with event propagation (that was another separate issue I was working on) - it was in this case preventDefault that was the issue.  Previously we relied on the default page down and page up behaviour to allow users to page up and down in a document that was zoomed in - we have decided to work around this by programmatically scrolling instead - so closing this for now.
