### ISSUE TITLE
Improve setHeaderItem to be able to update an item object

### ISSUE THREAD

**Issue by ZhijieZhang** [PDFTron/webviewer-ui#17]

**Comment by justinjung04** [comment]
Scope of this ticket has been expanded to rethinking of setHeaderItems and used-cases. This is not a high-priority for us, so we will revisit this enhancement ticket in future minor or major release.

**Comment by justinjung04** [comment]
Change in header item structure is addressed in dev branch, and it will be available in next release. Closing this ticket.
