### ISSUE TITLE
Position Sort Strategy doesn't take document orientation into account

### ISSUE THREAD

**Issue by henry-chris** [PDFTron/webviewer-ui#179]
Load a PDF built in landscape.  Place annotations, and sort by position.  Sort algo. only looks at Page -> Y coordinate.  In landscape Y coord is transformed to X coord so everything is sorted from left to right.

Intended?

**Comment by justinjung04** [comment]
Thank you for reporting the issue! No it's not intended, and I agree that it's more natural for it to take orientation into account.

Currently we are occupied with a new release coming up, but after that we'll work on updating this behavior.
