### ISSUE TITLE
Calling setFitMode on the viewer element doesn't work

### ISSUE THREAD

**Issue by mparizeau-pdftron** [PDFTron/webviewer-ui#186]
For example:
```
const viewer = new PDFTron.WebViewer({...});

viewerElement.addEventListener('documentLoaded', () => {
  viewer.setFitMode('FitPage');
});
```

This doesn't work because the functions for fit modes aren't implemented on the instance setup in index.js.

**Comment by ZhijieZhang** [comment]
We had a discussion internally and this issue is fixed by changing webviewer.js
