### ISSUE TITLE
Downloaded/Printed PDFs position annotations differently than in the Webviewer

### ISSUE THREAD

**Issue by henry-chris** [PDFTron/webviewer-ui#190]
Tested in Chrome 72
Windows 10 OS
Webviewer 4.1+

Most specifically with the Free Text annotation, but it may happen with others.

Repro steps:
1. Multi Page PDF (mine was loaded via only browser)
2. Mark it up with Free Text annotations (I had also places Rectangles throughout the document, and all my text annotations had some styling applied).
3. Download the PDF.  Free Text annotations may be positioned slightly differently and/or the border/size of the text window may be smaller/larger.
4. Print PDF.  Free Text annotations may be positioned differently and/or the border/size of the text window may be smaller/larger.

Printed PDFs were more drastically impacted in general.  Downloaded PDFs had some, but minimal impact.

I have the PDF handy, but would need to modify it before I gave it to you.  So, let me know if you can't repro.

**Comment by justinjung04** [comment]
Unfortunately we are having trouble reproducing the issue.
Could you provide us the PDF? Also, does the issue happen only in that PDF?

**Comment by henry-chris** [comment]
Sorry for taking so long to reply.  That PDF had PII in it.  I'm going to need to reproduce this and at the moment it's low on my list.  

It will probably be 2-3 weeks, feel free to do whatever you need to with this issue.

**Comment by henry-chris** [comment]
I've tracked this down a little more I think.  It seems that when you download and print certain annotations, the annotation is framed by it's Bounding Box in some situations.  When PDFs are resized or are printed/downloaded at a different scale the Bounding Box and annotation get moved a little bit.  

In some cases the annotations also seem to be scaled by the top left of the bounding box instead of the center.  So, it moves away from center when scaling.

How do you expect annotations to scale with the document in general?  Does each annotation behave differently?

**Comment by justinjung04** [comment]
Could you elaborate on your workflow and your expected result?
Do you see the odd behavior in some annotations only or all annotations?
Screenshots before/after the document scaling would also be super helpful.

**Comment by justinjung04** [comment]
Just wanted to follow up on this. Has this been fixed with our latest releases or is it still bothering you?

**Comment by henry-chris** [comment]
Sorry again, I had forgotten about my old issues.  

I just attempted to reproduce this several times and could not.  With the same PDF.  

I will try to keep a close eye out in case I see this again, but this can be closed.
