### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by uluzox** [PDFTron/webviewer-ui#204]
Hi, 
I checked out the v.5.0.0 branch and tried to run a `npm run build` after I did `npm install`. The build breaks with

```
ERROR in ./src/redux/initialState.js
Module not found: Error: Can't resolve 'components/toggleElementOverlay' in '/home/thersam/Projects/AKAD/pdf-tron/src/redux'
 @ ./src/redux/initialState.js 11:28-70
 @ ./src/redux/reducers/rootReducer.js
 @ ./src/index.js
 @ multi babel-polyfill ./src

ERROR in ./src/components/App/App.js
Module not found: Error: Can't resolve 'components/zoomOverlay' in '/home/thersam/Projects/AKAD/pdf-tron/src/components/App'
 @ ./src/components/App/App.js 127:19-52
 @ ./src/components/App/index.js
 @ ./src/index.js
 @ multi babel-polyfill ./src
```

I am using npm 6.9.0

Kind regards,

Thorsten

**Comment by justinjung04** [comment]
Hi Thorsten,
I tried downloading both master and 4.1.0 branch, and ran npm install && npm run build with node v11.11.0 (npm v6.9.0) but couldn't reproduce the issue.
Could you double check that your branch is up to date?

**Comment by uluzox** [comment]
Hi Justin,
I updated to the lastet node version but this did not help. I am able to build branch 4.1.0 but not the master nor the v5.0.0 branch.
My branch is up to date as I just cloned your repo.

Please find attached the "npm run build" output [build.log](https://github.com/PDFTron/webviewer-ui/files/2981985/build.log) and the debug log mentioned in the build output [debug.log](https://github.com/PDFTron/webviewer-ui/files/2981989/debug.log).

Kind regards,
Thorsten

**Comment by justinjung04** [comment]
Oh, it looks like some components were being imported with incorrect casing (zoomOverlay instead of ZoomOverlay) and macOS isn't case sensitive.
I just pushed a fix to master branch.

**Comment by uluzox** [comment]
Thank you, it works :+1:
