### ISSUE TITLE
Highlight menu appears when switching the tool mode and header is hidden

### ISSUE THREAD

**Issue by mparizeau-pdftron** [PDFTron/webviewer-ui#211]
To reproduce set the `disabledElements: ['header']` option in the constructor then programmatically call `readerControl.setToolMode('AnnotationCreateTextHighlight')`. You'll see a floating highlight menu that shouldn't be visible at all since the header is hidden.

From here https://groups.google.com/d/msg/pdfnet-webviewer/i2rRJkkrL_Y/Q-CLFheiBQAJ

**Comment by ZhijieZhang** [comment]
Close this issue for now since it should be fixed in this commit: https://github.com/PDFTron/webviewer-ui/commit/267e8a64c7d9ea85bf67d8dd2d51b54fdb5fc73c
