### ISSUE TITLE
ToolButtons do not propagate 'onclick' events

### ISSUE THREAD

**Issue by henry-chris** [PDFTron/webviewer-ui#217]
I began to fix and PR this, but figured there was a few ways of handling it on your end.

In the ZoomOverlay, if the 'MarqueeZoom' button is clicked it triggers the `onClick` function of the `<ToolButton>`.

The `onClick` of a `<ToolButton>` stops all event propagation, so the ZoomOverlay is never closed until another button is pressed.

This would happen for the new redact tool as well if it hooked into the `onClick` event.

See:  ToolButton.js -> onClick : ~ln 38
        ZoomOverlay.js -> render : ~ln 94

I doubt removing `e.stopPropagation()` is the answer, so I was looking at hooking into the `closeElements()` action instead of the singular one.  

I did briefly test that using `closeElement('zoomOverlay')'` solves the problem.

You guys also manage your popups/overlays strangely to me.  I had problems adding extra menus in the past until we made a react component which all our popups derive from and handles how to open/close things in a singular place.  Works for many of our custom elements, but maybe there is something I don't understand about your architecture.

### Additional Problems, See: ZoomOverlay.scss for the following.

**The MarqueeZoom overlay button does not have a hover color.**
I fixed that simply by doing - 

       .ToolButton{
         background: white;
         height: 35px;
         font-family: 'Roboto', sans-serif;
     
         // ** Add the below lines.
         &:hover {
           background: var(--button-hover-color);
          }
       }

**This seems like a bug (multiple background properties) -**

      .spacer{
        width: 146px;
        height: 1px;
        background: #F0F0F0;  // *******Probably need to remove this??
        background: var(--button-active-color);
      }

**Comment by justinjung04** [comment]
Thank you for your feedback.
Managing popups and overlays is indeed overwhelming, and we are planning to redesign it when we upgrade to the latest React.
It's also a mistake not to have hover color on marquee zoom button, but we intentionally add two background properties as css variables are not supported in IE11 (then it falls back to the hard-coded value above).

**Comment by henry-chris** [comment]
This has been resolved based on #349 and other fixes.
