### ISSUE TITLE
Change setNotesPanelSort API name to setSortStrategy

### ISSUE THREAD

**Issue by ZhijieZhang** [PDFTron/webviewer-ui#23]

**Comment by justinjung04** [comment]
- [ ] update variable name `sortNotesBy` to `sortStrategy` in redux
- [ ] add addSortStrategy api, which appends to sortMap constant
- [ ] add setSortStrategy api, which selects the strategy to sort the notes in UI
- [ ] add deprecation message to setNotesPanelSort (which switches to addSortStrategy) and setSortNotesBy (which switches to setSortStrategy)
