### ISSUE TITLE
Using controls when no document is loaded causes UI to crash

### ISSUE THREAD

**Issue by lbittner-pdftron** [PDFTron/webviewer-ui#251]
The following operations break when no document is loaded:
- Search
- Rotate
- Signature Rule
- Download
- Print 

Maybe these tools (or all tools) should be disabled when no document is loaded?

**Comment by ZhijieZhang** [comment]
I will close this issue for now as [a PR](https://github.com/XodoDocs/webviewer/pull/215) has been made to address it.
