### ISSUE TITLE
Documentation for Layout Modes not correct

### ISSUE THREAD

**Issue by shmarlya** [PDFTron/webviewer-ui#281]
Accoridng to docs api there are few layout modes:
Continuous, - works
**FacingCoverContinuous - not works,**
Facing - works,
FacingContinuous - works,
**FacingCover - not works,**
Single - works

Link in api docs:
https://www.pdftron.com/api/web/PDFTron.WebViewer.html#LayoutMode__anchor

In reality something like this
https://github.com/PDFTron/webviewer-ui/blob/bf8b4519b69f9339d09145ab78387c68fad7e409/src/constants/layoutMode.js

How to reporduce:
try to call method with one in list of params above that doesnt work,
`setLayoutMode()`

**Edited:
Correct list of params look like here:
https://www.pdftron.com/api/web/CoreControls.html#.DisplayModes__anchor**

Please make sure that your docs are correct, ty.

**Comment by justinjung04** [comment]
Hello,

`LayoutMode` is an enum that contains string values, so the values that you see in the api doc are the keys, not the string values themselves. For example,
```javascript
LayoutMode. FacingCoverContinuous === 'Cover'
setLayoutMode('FacingCoverContinuous') // incorrect
setLayoutMode(LayoutMode.FacingCoverContinuous) // correct
```
It's not very intuitive, but it was an intermediate solution for backwards compatibility, which hopefully we can clean up one day.

I've updated the examples in the api doc to make it clearer.
Please let me know if you have further questions.

**Comment by shmarlya** [comment]
@justinjung04  thanks, i've close the issue
