### ISSUE TITLE
Create an API for custom tabs and panels in left panel

### ISSUE THREAD

**Issue by ZhijieZhang** [PDFTron/webviewer-ui#29]

**Comment by sabieber** [comment]
The new API is really nice 👍
Only thing i noticed with it is that it does not add the normal `Panel` class the normal panes have to the created DOM element. Could this be improved when rendering the custom panel?

**Comment by ZhijieZhang** [comment]
Hi there! What you are suggesting definitely makes sense, we will add it soon. Thanks for you reply
