### ISSUE TITLE
getPassword callback

### ISSUE THREAD

**Issue by glendaviesnz** [PDFTron/webviewer-ui#33]
The getPassword callback to automatically pass in the pdf password and bypass the user prompt does not work in the new UI  - if we use the legacy UI it works as expected. 

Is this call back still available in the new UI and if so how do we use it, can’t find anything in the docs?

**Comment by justinjung04** [comment]
Right now there isn't an easy way for users to configure it. We'll come up with a better API soon!

**Comment by glendaviesnz** [comment]
Thanks Justin - FYI, we have pulled this change and it is working for us.
