### ISSUE TITLE
Cannot have image and label in Button.js

### ISSUE THREAD

**Issue by henry-chris** [PDFTron/webviewer-ui#359]
Looks like in 5.2 you changed where a button could not have an image and a label at the same time.  I have a button in the header which displays # of concurrent users in a document.  It's not the best, but it works.
![image](https://user-images.githubusercontent.com/4165721/65067457-2c91b800-d94c-11e9-9d8f-b1e00a7731cc.png)

After updating to 5.2 I cannot do that using your built in system.  Possible to get that changed back?  I'm currently just changing the file to get it to work for now.

**Comment by mparizeau-pdftron** [comment]
It looks like the relevant change was here https://github.com/PDFTron/webviewer-ui/commit/7b888c1f67f204f84d7b5cba02c603a615a104f4#diff-d1110304895e39c6e9fd2be689023291

I believe the logic was being cleaned up as part of refactoring and the original intent wasn't to have both at the same time. However it seems reasonable that you might want to have a button that has an icon and a label at the same time.

We'll discuss internally about allowing this behavior explicitly and making sure it's documented correctly.

**Comment by ZhijieZhang** [comment]
We decided to bring it back as we noticed that in our new UI design we actually have cases where a label and an image are both used. The change will be available in 6.1, which we aim to release at the end of this month. 

Let me know if you'd like me to back merge this change to the version you are using! :)

**Comment by henry-chris** [comment]
Nope, it's fine.  I just put it back in manually.

**Comment by ZhijieZhang** [comment]
Thanks. I will close this issue for now as it's been addressed in 6.1. Feel free to follow up if you have any other questions. Thanks!
