### ISSUE TITLE
Pages not rendering on document load

### ISSUE THREAD

**Issue by henry-chris** [PDFTron/webviewer-ui#362]
Picture should say it all.  I've been getting this error off and on.  In this case I'm using the WV Server to serve the PDF.  On Chrome 77.  Screenshot has versions.  The UI version is actually 5.2.3.  My package.json isn't in the same place as yours, so I just manually update the value and I forgot this time.

![image](https://user-images.githubusercontent.com/4165721/65730556-d1686f80-e087-11e9-9702-ae51f25f516c.png)

**Comment by ZhijieZhang** [comment]
Thanks for bringing this up. I'm having some trouble reproducing the issue.

I used WebViewer 5.2.3 with WVS(`https://demo.pdftron.com/`) in Chrome 77 and tried to load documents with different pages, but wan't able to see this error message.

Would it be possible for you to send the document to us? You can send it by opening a support ticket via https://www.pdftron.com/form/request. Thanks!

**Comment by henry-chris** [comment]
It doesn't seem to be document related.  I've only had it happen 3 times in a few weeks, I'm just not sure why.  If it happens again I will be sure to save more metadata to send.

**Comment by henry-chris** [comment]
Closing.  This was found to be fixed when we upgraded to a new version and Core.  Not sure why it sometimes manifested.
