### ISSUE TITLE
Suggestion - Remove Babel/Polyfill

### ISSUE THREAD

**Issue by henry-chris** [PDFTron/webviewer-ui#375]
I have done this in my own build of webviewer.

See here: https://babeljs.io/docs/en/babel-polyfill#docsNav

Suggestion is to remove polyfill and include 2 other files directly.

You should be able to remove the polyfill inclusion in the webpack/config and then import the following in the main index.js.

import 'core-js/stable';
import 'regenerator-runtime/runtime';

Sorry I did not make a PR myself as it would be an easy change.

**Comment by ZhijieZhang** [comment]
Thanks! This definitely makes sense. Will make this change as soon as 6.0-beta is out.

**Comment by ZhijieZhang** [comment]
Hi Chris,

We just released the 6.0-beta, which can be downloaded from https://www.pdftron.com/downloads/WebViewer-6.0.0-beta-1.zip.
We also have a migration guide here https://www.pdftron.com/documentation/web/get-started/migrating-to-v6.

You can see that we're not using `@babel/polyfill` https://github.com/PDFTron/webviewer-ui/blob/37a4671ccae1b693fc1d47800200c1bb24145fd8/webpack.config.prod.js#L8.

I will close this issue for now. But do please let me know if you found any issues or you have further questions. Thanks!
