### ISSUE TITLE
Suggestion - Removing zoom tools on large touch screen devices (specifically iPad)

### ISSUE THREAD

**Issue by IsuruNana** [PDFTron/webviewer-ui#377]
I believe it would be beneficial to take out the zoom tools (+ and - buttons) as well as the percentage zoom dropdown on large handheld devices like the iPad. 

Since users can pinch to zoom taking them out would increase screen real estate to add the annotation icons in the header.

Screenshot taken on:

iPad Pro 10.5 inch - iOS 13.1.2 - Running iOS Chrome 77.0.3865.103 

![issue3](https://user-images.githubusercontent.com/16419053/66774675-c5521f80-ee87-11e9-8959-d66950541f4a.png)

**Comment by IsuruNana** [comment]
Nevermind I see the customization for headers section

**Comment by ZhijieZhang** [comment]
Hi,

Our intention is to hide the zoom list and the marquee zoom tool in touch devices. Technically you can hide it using the `setHeaderItems` API, but it looks like a bug on our side. We will take a look tomorrow as today is a stat holiday in Canada. Thanks for bringing this to our attention.

**Comment by ZhijieZhang** [comment]
Nvm, I checked the code and realized that our intention was to only hide the marquee zoom tool in touch devices. That said, I don't think this is an issue on our end, and you can use `setHeaderItems` to hide the zoom indicator and the dropdown list!

**Comment by IsuruNana** [comment]
Sounds good will do that.
