### ISSUE TITLE
Polyline, Polygon and Cloud annotation markup is broken on iPad

### ISSUE THREAD

**Issue by IsuruNana** [PDFTron/webviewer-ui#378]
After making a Polyline, Polygon or Cloud annotation on the iPad Pro 10.5 inch, hitting save (the tick mark) doesn't save the annotation and erases the annotation from the screen.

Can be reproduced on the Webviewer demo on iPad

GIF recorded on:

iPad Pro 10.5 inch - iOS 13.1.2 - Running iOS Chrome 77.0.3865.103

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/16419053/66775586-03504300-ee8a-11e9-9edb-2c918a25a5f8.gif)

**Comment by ZhijieZhang** [comment]
Yeah we recently noticed that the checkmark button is kind of misleading. It doesn't actually mean 'save' the current drawing annotation, but means something like 'I've finished drawing the annotation, and I want to switch to the default tool(which is the hand tool in mobile I think)'. 

Our UX is looking for a better way to display this button(may a different location, or a different image). It seems that WebViewer doesn't expose an API to programmatically finish the drawing process of these three tools to make the annotation 'stay', so users have to double tap the screen to complete the annotation in touch devices.

One option I think you can do on your end is to change the icon of this icon to be a 'cross' to avoid confusion. To do this, change the `img` prop to `ic_close_black_24px`.

https://github.com/PDFTron/webviewer-ui/blob/436167f099126636b67eadf4a2dafda1c6ac5004/src/components/ToolsOverlay/ToolsOverlay.js#L143-L147

**Comment by IsuruNana** [comment]
Thanks for the feedback. I'll see what I can do to work through that.

**Comment by ZhijieZhang** [comment]
I'm closing this for now due to inactivity. Aiming to improve mobile user experiences is one of our goals this year and I believe this is one of the items that we will be addressed.
