### ISSUE TITLE
Thumbnail page is not scrolling as we are scrolling the viewer

### ISSUE THREAD

**Issue by andreysaf** [PDFTron/webviewer-ui#380]
In Adobe Reader or Mac Preview, as you scroll the document, the thumbnail pages are scrolling as well.

**Comment by sanioka** [comment]
Also when I use setCurrentPage(n) API method, I need to scroll thumbnails to the same {n} page.

**Comment by ZhijieZhang** [comment]
Thanks for bringing this up. We've put this in the backlog and will have this feature implemented in a near future.

> Also when I use setCurrentPage(n) API method, I need to scroll thumbnails to the same {n} page.
Hmm, I think this will be achieved without any extra effort after we sync the scrolling between main document container and the thumbnails panel.

**Comment by ZhijieZhang** [comment]
Just let you know that this feature will be part of the 6.0-beta release. Below is a gif showing what it will look like:

![gif](https://user-images.githubusercontent.com/25110092/67891990-f762b300-fb10-11e9-9509-ae515851b1c8.gif)

**Comment by sanioka** [comment]
Awesome!

**Comment by ZhijieZhang** [comment]
@sanioka 

Hi,

We just released the 6.0-beta, which can be downloaded from https://www.pdftron.com/downloads/WebViewer-6.0.0-beta-1.zip.
We also have a migration guide here https://www.pdftron.com/documentation/web/get-started/migrating-to-v6.
You should be able to see the thumbnails panel scroll when you scroll the document. Do let us know if you found any issues or you have any further questions.

**Comment by sanioka** [comment]
Thank you!

**Comment by ZhijieZhang** [comment]
Hmm actually I just tested it and it seems that we introduced a regression recently which causes this doesn't work in the beta-1 build. I just fixed it and will let you know after the fix is in the beta build. 

Sorry for the inconvenience :/

**Comment by sanioka** [comment]
Ok, I will wait for news from you.

**Comment by ZhijieZhang** [comment]
Hello!

Sorry for the delay, but WebViewer 6.0 is officially released. We've updated our online samples to use 6.0 so you can play around with the thumbnail scrolling here https://www.pdftron.com/samples/web/samples/viewing/viewing/

Let me know how this works for you and if you have any other questions. Have a nice day!

**Comment by ZhijieZhang** [comment]
I'm going to close this issue for now. But do feel free to reopen it if you found any issues. Thanks for the suggestion.
