### ISSUE TITLE
Mispositioning when zoom in on mobile

### ISSUE THREAD

**Issue by BaZzz01010101** [PDFTron/webviewer-ui#393]
Version: 5.2.4.72582 (not fixed in 5.2.7.72921)
Browser: Mobile Chrome 77.0.3865.116

Steps to reproduce:
1. open https://www.pdftron.com/webviewer/demo/ on mobile phone
2. zoom in significantly any area in document trying to keep some part of content on the screen
3. release both fingers simultaneously
Content will be shifted by some amount which depends on zoom change.

Expected behaviour:
Content should not shift and stay in visible area after zoom end.

**Comment by ZhijieZhang** [comment]
Thanks for reaching out.

We are aware of this issue and will look into this in this month.

**Comment by mbr93** [comment]
Any progress on that? This is the issue for us, as well.

**Comment by ZhijieZhang** [comment]
Hey. I briefly looked into this issue but was pulled away by other tasks. I think I should have some time look into this further next week. Let me know if you have any concerns.

**Comment by ZhijieZhang** [comment]
Hi guys, we've made a fix to the issue internally. It'll very likely be in 6.1. Please let me know if you guys want a custom build to try, or would like this fix to be back merged.

**Comment by BaZzz01010101** [comment]
Hi @ZhijieZhang 
We have a lot of own integrations in v5 and too limited with time now to move to v6.
It would be great to have a build of WebViewer v5 with this fix.
Thanks

**Comment by ZhijieZhang** [comment]
Hello!

Thanks for getting back to me. I've back merged the fix to 5.2.x and 6.0.x. Tomorrow you can try the stable nightly build from https://www.pdftron.com/nightly/#stable/ which should contain the fix. Let me know if you have any other questions. Have a nice day!

**Comment by ZhijieZhang** [comment]
I will close this issue for now as the issue should be fixed with the latest nightly build for both 5.2.x and 6.0.x. However feel free to reopen it if you found any issues. Thanks guys!
