### ISSUE TITLE
Config in URL not supported

### ISSUE THREAD

**Issue by michaelpeterlee** [PDFTron/webviewer-ui#399]
Re: http://localhost:3000/#d=https://pdftron.s3.amazonaws.com/downloads/pl/demo-annotated.pdf&a=1&config=viewer-config.js

Chrome inspector reveals no network request for this resource.

Q. How do we develop in association with a custom config file ?

**Comment by ZhijieZhang** [comment]
We stopped passing the config file path to the UI as part of its URL to prevent potential XSS attack.
If you'd like to load your own config while developing the UI, please make a change to this file:
https://github.com/PDFTron/webviewer-ui/blob/60eeaf0f73990e39462f0d8ba8c28315f87a5bd7/src/helpers/loadScript.js#L26-L29

Instead of just calling `resolve()`, try using the `loadScript` function like below:
```javascript
loadScript('viewer-config.js').then(resolve)
```

**Comment by ZhijieZhang** [comment]
Hi Mike, just want to follow up to see how it works for you and if you have any other questions.

**Comment by michaelpeterlee** [comment]
Thanks Zhijie, that resolves the config.

You may like to consider that as the new default and expose that somewhere else, else folks have to fiddle there to develop which is not intuitive.

**Comment by michaelpeterlee** [comment]
Re: $(document).on('documentLoaded') 

This event does not fire in the config file, investigating further now.

**Comment by ZhijieZhang** [comment]
Hmm I can't seem to reproduce the issue. Here are the steps that I took:

1. create a `config.js` inside the `assets` folder.
2. have the following code in `config.js`:
```javascript
$(document).on('documentLoaded', () => {
  console.log('document just loaded!');
});
```
3. open `loadScript.js`, change line 28 to
```javascript
loadScript('/assets/config.js').then(resolve);
```
4. `npm start`
5. After the document is loaded, I see `document just loaded!` in the console, which indicates that the config file is working.

I'd like to confirm first that your config file is actually be requested? You can use the Chrome dev tools, network tab to check if there's a request sent to your config file. It'd be also helpful if you can send me a sample project in which I can reproduce the issue. Thanks!

**Comment by michaelpeterlee** [comment]
We now find that 'documentLoaded' fires but 'viewerLoaded' does not. Investigating further now..

**Comment by michaelpeterlee** [comment]
We replaced our `viewer-config.js` with just the listeners and it works. So something is bombing silently in our config file. Thanks for your help to confirm things work after editing the loadScript helper.
