### ISSUE TITLE
setNotesPanelSort won't trigger resorting

### ISSUE THREAD

**Issue by sabieber** [PDFTron/webviewer-ui#40]
Calling the function multiple times with different or altered objects (e.g. for applying filters) won't retrigger the sorting/displaying of the annotations in the annotations panel.

**Comment by sabieber** [comment]
It seems to only work when the user switches to another leftpanel tab and then back to the notes.
What we try to accomplish is a toggle inside of the notes panels where the user can toggle between two different sortings.

This is the sort strategy:
```
var noFilter = function (notes) {
        return notes;
    }

    var filterRevised = function (notes) {
        return notes.filter(function (note) {
            return !note.oxomiRevised && note.getContents();
        });
    }

    var oxomiSortStrategy = {
        getSortedNotes: function (notes) {
            return oxomiSortStrategy.filter(notes).sort(function (a, b) {
                // Sort by reading order (top to bottom left to right)
                var verticalDiff = a.getY() - b.getY();
                if (verticalDiff !== 0) {
                    return verticalDiff;
                }
                return a.getX() - b.getX();
            });
        },

        shouldRenderSeperator: function (previous, current) {
            return current.PageNumber !== previous.PageNumber;
        },

        getSeperatorContent: function (previous, current) {
            return current.PageNumber;
        },

        filter: noFilter
    };
```

And this is where we switch between the filters and reapply the sort strategy:
```
Config.showAllAnnotations = function () {
            oxomiSortStrategy.filter = noFilter;
            readerControl.setNotesPanelSort(oxomiSortStrategy);
        }
        Config.showOpenAnnotations = function () {
            oxomiSortStrategy.filter = filterRevised;
            readerControl.setNotesPanelSort(oxomiSortStrategy);
        }
```

This is the current workaround:
```
        Config.showAllAnnotations = function () {
            oxomiSortStrategy.filter = noFilter;
            readerControl.setSortNotesBy('position');
            readerControl.setNotesPanelSort(oxomiSortStrategy);
        }
```

**Comment by sabieber** [comment]
After inspecting the code I fixed it by changing it to two separate sort strategies with names, registering them and switching by calling `setSortNotesBy` and their name.

The issue I see here is that documentation for `setNotesPanelSort` and the sort object (with methods `getSortedNotes`, `shouldRenderSeperator`, `getSeperatorContent` and the `name` field) is missing completely here: https://www.pdftron.com/documentation/web/guides/ui/apis

**Comment by ZhijieZhang** [comment]
Good to hear you fixed it! We didn't mean to make this API public yet, that's why the documentation is missing in the APIs section. We were planning to squash new APIs and make them public with proper documentation in the next minor release. Sorry for the confusion, we made a mistake as we shouldn't merge this new API into master until the next release. We will be careful next time! Please note that we may also change the name of this API. We will let you know when we changed it

**Comment by sabieber** [comment]
Thanks for the info and the heads up 👍
