### ISSUE TITLE
Disable switching pages

### ISSUE THREAD

**Issue by yty-agnitio** [PDFTron/webviewer-ui#401]
How can I disable switching pages for the users (since I will be switching the pages for them remotely using WebSockets)?

**Comment by ZhijieZhang** [comment]
Hi,

You can comment this line out https://github.com/PDFTron/webviewer-ui/blob/master/src/components/DocumentContainer/DocumentContainer.js#L101 to disable scrolling pages in the single display mode. And then you can use setLayoutMode to set the layout mode to be single on every document loaded.

```javascript
instance.docViewer.on('documentLoaded', () => {
  instance.setLayoutMode(instance.LayoutMode.Single);
});
```

**Comment by ZhijieZhang** [comment]
@yty-agnitio Just wanna follow up to see how this works for you. Let me know if you have any other questions. Happy to help!

**Comment by yty-agnitio** [comment]
@ZhijieZhang, It worked. Thank you!

**Comment by ZhijieZhang** [comment]
Thanks for confirming. I will close this issue now. Feel free to reopen it if you have any further questions. Thanks!

**Comment by yty-agnitio** [comment]
Hi again.
I just realized that I also need to prevent some users from swiping pages as well. 
Actually I need to prevent all possible ways of switching pages but only for some users (programmatically on condition). Is there any api for that, or please advise how I can achieve that.

**Comment by ZhijieZhang** [comment]
Hello!

Sorry for the delay in the response. Currently there's no API to disable swiping to go to different pages so you need to modify the UI source code.

The code you'd want to comment out is below
https://github.com/PDFTron/webviewer-ui/blob/75d805a2f8650401f34f85edbb62dcc29b8534fa/src/helpers/TouchEventManager.js#L210-L214

I think it makes sense that we can provide an API to disable all the ways to navigate to different pages. This includes `arrowUp`, `arrowDown`, `wheel`, `swipe`. Not sure if we should remove the button that is used for changing the layout mode to continuous scrolling though. Are you using single page layout mode in your app, and never use continuous scrolling?

Adding this API shouldn't be a tricky change but currently we are working on testing for 6.1 release so I don't have a timeline for this yet. Let me know if you have any concerns or questions. Thanks!

**Comment by ZhijieZhang** [comment]
Hello there. We've added an option to disable all the page navigations in WebViewer.

```javascript
instance.disableFeatures([instance.Feature.PageNavigation])
```

This option will be available in 6.1. I'm going to close this issue for now but feel free to ask any questions. Thanks for bringing this topic up and have a nice day!

**Comment by rammathaakur** [comment]
we have to disable swipe feature we have try with
if (is_touch_enabled()) {
readerControl.disableFeatures([readerControl.Feature.PageNavigation]);
}
this code work but side effect are also coming like on zoom we can't move in all direction we can only move if verticle or horizontal, please advise how I can achieve that without having any other issue

**Comment by bollain** [comment]
Hi @ShyamCIS, 

For this issue it is best if you submit a request to our support team so it is properly triaged:
https://support.apryse.com/support/tickets/new

Please include all relevant info like version number and repro steps with any code you are using.
