### ISSUE TITLE
Global onkey listeners interfering with normal use

### ISSUE THREAD

**Issue by ascherer1993** [PDFTron/webviewer-ui#41]
Key listeners are causing problems when using other parts of the application. 

Example/How to reproduce
1.  Create an annotation
2.  Open the notes panel
3.  Create several comments on the annotation
4.  Try to copy text from another comment using ctrl + C and try to paste it into the reply text area with ctrl + V. You should notice that you have ended up creating a copy of the annotation that was selected.

We noticed this when implementing a custom modal and these actions were being performed behind our modal. If there is a way to avoid these issues that would be helpful.

**Comment by justinjung04** [comment]
We reproduced the issue. We'll come up with a fix soon!

**Comment by henry-chris** [comment]
@justinjung04 Please note that it's not just ctrl C.  It's all hotkeys.  Delete, ctrl+v, backspace, etc...  And for prettymuch all context menus/modals.
