### ISSUE TITLE
Panel buttons rounded corner rendering issue

### ISSUE THREAD

**Issue by Camo30** [PDFTron/webviewer-ui#412]
There is a small rendering issue with the rounded corners. Please see the attached pictures.

Version: 5.2.4.72582 (not fixed in 5.2.8.73151/6.0.0 beta1)
Browser: Chrome 78.0.3904.97

Steps to reproduce:

1. open https://www.pdftron.com/webviewer/demo/
1. open side panel (e.g. thumbnail view)
1. focus on the left panel tab buttons, the rounded corners are not rendered correctly. It's best visible when zooming in (using browser zoom)

Expected behaviour:
The rounded corners should be rendered correctly. Seems to be caused by the background color from the buttons.

Current state:
![wrong](https://user-images.githubusercontent.com/33700436/69033868-37b2a400-09e0-11ea-99c5-c9edc30aa1a2.jpg)

Correct rendering:
![correct](https://user-images.githubusercontent.com/33700436/69033877-3bdec180-09e0-11ea-88b3-b5478496046d.jpg)

Got correct rendering by adjusting this style:
![style](https://user-images.githubusercontent.com/33700436/69033968-70eb1400-09e0-11ea-8b12-4bbcc96f0b81.jpg)

**Comment by ZhijieZhang** [comment]
Hey thanks for brining this up :)

I fixed this issue in https://github.com/PDFTron/webviewer-ui/commit/887822f38124572d7aa66e7bb0e639c71837a7a4.

Let me know if you need a build with the fix right away. If the fix isn't urgent for you then you can wait for the next release which will include it, and I will close the issue.

**Comment by Camo30** [comment]
Thank you, this is not urgent, so I'll wait for the next release
