### ISSUE TITLE
Text annotation sometimes ends up wrapping last character after save and reload

### ISSUE THREAD

**Issue by ghills** [PDFTron/webviewer-ui#421]
We have occasionally been seeing an issue where free text annotation is added (by clicking a single position, entering text, allowing bounding box to be automatically fit to entered text) then after saving the file and reloading the page the annotation is then left where the last character of the text is then missing as it was wrapped to the next line (but doesn't fit in viewable area). Here is a screenshot of it where you just barely see the top of the second line:

![image](https://user-images.githubusercontent.com/87394/69579126-c1391780-0f86-11ea-90cc-11587f154c86.png)

We have had trouble reproducing it consistently which led me to believe it had something to do with rounding based on the exact width and position. By checking the position of an affected annotation I think I have steps to reproduce it:

1. Add free text annotation with text "11/23/2019" by selecting single point, entering text, then allowing size to be set around text automatically. (Helvetica 12pt)
2. Using the JS API, move the annotation to an X position of `452.33`.
3. Save document with annotations embedded.
4. Reload document into webviewer.

Before reloading '11/23/2019' should have been all shown on 1 line, as expected. After reopening it shows up as '11/23/201' on the first line, 9 wrapped out of view.

I have suspected that it may be related to #190

**Comment by ghills** [comment]
To be clear - when this is actually happening we are not programmatically moving the annotations. That is simply used to get a very specific position based on the position of a real world example that happened.

**Comment by ZhijieZhang** [comment]
Hi,

Thanks for reaching out. We've received your ticket at https://support.pdftron.com/a/tickets/9351. So I will close this issue and continue our conversation in the ticket.

I don't think I have enough time today to investigate it, but should be able to get back to you by the end of tomorrow.

Let me know if you have any concerns or questions. Thanks!
