### ISSUE TITLE
Redux 'isReadOnly' different from core.getIsReadOnly()

### ISSUE THREAD

**Issue by henry-chris** [PDFTron/webviewer-ui#426]
Title says most of it.

These two are not synced in any way.  This can lead to weird cases where you set one to false and the other is true or vice versa.

**Comment by ZhijieZhang** [comment]
Hmm do you mind showing me an example about how you use it? I can't seem to reproduce it.

![Screen Shot 2019-11-29 at 10 27 27 AM](https://user-images.githubusercontent.com/25110092/69885621-e5506d80-1292-11ea-9643-60384fd48d87.png)

![Screen Shot 2019-11-29 at 10 28 38 AM](https://user-images.githubusercontent.com/25110092/69885646-087b1d00-1293-11ea-962c-8f699ad6cda2.png)

This is where we are trying to sync them up https://github.com/PDFTron/webviewer-ui/blob/dev/src/event-listeners/onUpdateAnnotationPermission.js.

Let me know if anything is unclear and if I miss something. Have a nice day!

**Comment by henry-chris** [comment]
Hrmm.  I'll take a look at what you posted.

I am doing the following:
1. Call redux action - `dispatch(actions.setReadOnly(true));`
2. View readonly state from Core  - `const isReadonly core.getIsReadOnly();`
3. I am not using annotation manager methods. Should I be?  I'm confused as to what I should and should not be using.

I haven't looked at the event-listener stuff.

**Comment by henry-chris** [comment]
When using the AnnotationManager the problem seems to be fixed due to the permission event you linked.

I'm just still unsure as to what parts of which APIs to use and what drawbacks each of them have.  Core, docViewer/AnnotManager, Redux actions.  

I guess, the fact that SET_READ_ONLY is an 'internal' action should have been a clue to us, though.  It's just weird when part of the store needs specialized apis vs being built in to actions.

Maybe I'm wrong here again, though.  Any information would be helpful.

**Comment by henry-chris** [comment]
I'll close this as the problem is fixed.  More information would help, but I guess it's a fairly vague question(s).
