### ISSUE TITLE
Print option in drop down does not work most of the time

### ISSUE THREAD

**Issue by henry-chris** [PDFTron/webviewer-ui#44]
In the beta you had a PrintModal that popped up when you hit print.  That seems to still exist, but it either is no longer hooked up (it definitely seemed unfinished at the time) or is for different cases than we are using.  I honestly haven't looked into that too much.

However, if you just open up https://www.pdftron.com/webviewer/demo/
1. Attempt to print the default PDF you display in just about any browser.
- Results
-- Chrome opens new tab and shows 'preparing to print'.  Sometimes it actually shows the Chrome Print popup...but not usually.
-- Firefox does pretty much the same thing.  Opens a new tab and does nothing.
-- IE11 displays the loading modal indefinitely
-- Edge displays the loading modal indefinitely

Expected Behavior:  Printing displays modal or opens up browser specific print dialog that allows user to print the PDF.

**Comment by justinjung04** [comment]
Thank you for your report! We were able to reproduce the issue. It must be an error from the pdftron server. We will investigate it further.

**Comment by henry-chris** [comment]
Happens without only the client running also.  For us at least.
________________________________

**Comment by justinjung04** [comment]
The issue from the pdftronServer has been resolved. Could you check again to see if you can still reproduce the issues?

If it happens in the client-only mode too, could you elaborate what steps you took and what the results look like?

**Comment by henry-chris** [comment]
We are just using 4.0.1 of the WebViewer and the issues with Print happen.  No Server involved, just load any PDF at all.  I'm evaluating a couple other fixes currently give me a few days and I will test the Demo server and the client here.

**Comment by henry-chris** [comment]
This 'Seems' to be working correctly in a 4.0.2.X version of the viewer.  I will let you know if we experience any more issues.

**Comment by justinjung04** [comment]
Ok! We'll close this for now then.
