### ISSUE TITLE
Downloading Text Markups incorrect

### ISSUE THREAD

**Issue by henry-chris** [PDFTron/webviewer-ui#442]
Hello.  Two problems.

[WebViewer] UI version: 5.2.81, Core version: 5.2.8.73410 WebViewer Server: false Full API: false

Reproduced on several browsers.  Chrome is one.
**1. Text cut off when downloading/printing text annotations.**
a. Go here - https://www.pdftron.com/webviewer/demo/
b. Add text annotations.  Shouldn't matter how, but here is what I have.
![image](https://user-images.githubusercontent.com/4165721/71055590-d9cac680-211b-11ea-96cc-e90e06ff2bce.png)
c. Download PDF
d. Open downloaded PDF.  PDF text annotation should be cut off.
![image](https://user-images.githubusercontent.com/4165721/71055655-1ac2db00-211c-11ea-8a0d-cd591b01203b.png)

I also have a problem in Edge with Text Markups disappearing entirely when downloaded in Edge when using the WV server.  I will raise that in a ticket on the website unless you would like information here.

**Comment by ZhijieZhang** [comment]
Hi,

I'm able to reproduce the issue when the right border is close to the end of the text.

An appearance is added to annotations when a document is downloaded. When the document is reopened in WebViewer all annotations will be drawn according to their appearance until they are modified. So currently if you resize the box a little bit or even just change it text color, you will see the text no longer being cut off.

We noticed that when appearance of a freetext annotation is not used, WebViewer renders the text closer to the left and top border than Acrobat does. So we plan to update the freetext annotation rendering to be a bit closer to what Acrobat has -- by adding more padding to left, top and right. Hopefully this will solve the line breaking issue automatically. It may take some time as it's a bit tricky to ensure everything else still works(selection, doubling clicking, etc)

For the WebViewer Server issue could you please open a ticket for that? Thanks!

**Comment by ZhijieZhang** [comment]
Hi,

I just verified that the fix for this issue is in the latest nightly build. https://www.pdftron.com/nightly/#stable/2019-12-31/

Can you try it out and let us know how it goes? Please note that the fix is in v6.0 and wasn't picked back to v5.2. Let us know if you'd like the fix to be in 5.2 as well. Thanks!

**Comment by henry-chris** [comment]
Gonna be awhile before I can test.  With lots of UI level changes merging takes a bit.  Feel free to close if you feel it's fixed, and I will re-open when we migrate to v6.0.

**Comment by ZhijieZhang** [comment]
Going to close this issue for now. Please feel free to reopen this if you found any issues. Thanks.
