### ISSUE TITLE
Disabled notes panel - no initial selection

### ISSUE THREAD

**Issue by Camo30** [PDFTron/webviewer-ui#453]
When the notes panel is disabled there is no initial selection when opening the side panel. When selecting it manually it works.

Version: 6.0.2 Build "MTIvMzEvMjAxOXxjZjU4NjA3NQ=="
Browser: Chrome 79.0.3945.88

**Requirements:**

Use the following code as the constructor to initialize webviewer  
``` TS
WebViewer(
  {
    path: '../../../lib',
	backendType: 'ems',
    initialDoc: 'https://pdftron.s3.amazonaws.com/downloads/pl/demo-annotated.pdf',
  },
  document.getElementById('viewer')
).then(function(instance) {
	instance.disableFeatures(["NotesPanel"]);
});
```

**Steps to reproduce:**

1. open demo app
1. open side panel with the UI button
1. no initial selection and no content visible - manually selection works. reopening the panel after selection works.

**Expected behavior:**

- When the notes panel is disabled it should preselect the thumbnail panel or the outline panel.

Please see the attached sample GIF:
![notespanel](https://user-images.githubusercontent.com/33700436/71667998-99985480-2d67-11ea-9dee-c8355a20367e.gif)

**Comment by ZhijieZhang** [comment]
Hi,

Thanks for the detailed information and sorry for the delay in the response.

To set the active tab after the notes panel is disabled you can use [setActiveLeftPanel](https://www.pdftron.com/api/web/WebViewerInstance.html#setActiveLeftPanel__anchor). For example:

```javascript
instance.setActiveLeftPanel('thumbnailsPanel');
```

Let me know how this works for you and if you have any other questions. Have a nice day!

**Comment by Camo30** [comment]
Hi, thank you, it works.
