### ISSUE TITLE
[Full Api] Making Annotations in Document Compare mode with different sized pages

### ISSUE THREAD

**Issue by IsuruNana** [PDFTron/webviewer-ui#469]
### Background Information

When using the Document Compare API, the resulting diff document will be as big as the largest of the 2 pages being compared.

With our current setup, making an annotation on the Diff Document will mark an annotation on Document A (shown in red) 

![image](https://user-images.githubusercontent.com/16419053/72445191-f12abd00-3776-11ea-805f-8e6763cdc140.png)

### The Problem

![image](https://user-images.githubusercontent.com/16419053/72447350-d0fcfd00-377a-11ea-9cc9-e508e441fcc8.png)

When you exit the Document Compare and return to Document A, the annotation is cutoff. This is because Document B (shown in blue) has a bigger page size so the diff document was blown up to match it. Any annotations made outside the border of Document A in Doc Compare mode will be cutoff.

### Potential Solution

Have an indication of the border of the smaller document so users can have a visual cue of where to mark their annotations and keep within the bounds of that document.

_Document A border shown in red:_

![doc-border](https://user-images.githubusercontent.com/16419053/72447746-7dd77a00-377b-11ea-975d-779e83394c90.png)

Any other solution that would highlight the sizes of the two pages being compared would be helpful.

**Comment by ZhijieZhang** [comment]
Hello, sorry for the delay in the response. I'm going to take a look now and see what I can find.

**Comment by ZhijieZhang** [comment]
Okay! Here is what I found, hopefully it's helpful.

I'm assuming you are using the `appendVisualDiff` API with full api so I'm going to refer to the [this sample](https://www.pdftron.com/samples/web/samples/full-apis/ViewerPDFDiffTest/) which uses this API.

After we finish creating the diff document and before we call loadDocument with the `newDoc` we can listen to the `pageComplete` event and then in the event handler we can grab the page canvas, and use `ctx.strokeRect` to draw the boundaries of the documents. You can get the boundaries using the [getCropBox](https://www.pdftron.com/api/web/PDFNet.Page.html#getCropBox__anchor) API. The code would look like this:

```javascript
readerControl.docViewer.off('pageComplete.viewerDiff');
readerControl.docViewer.on('pageComplete.viewerDiff', async(index, canvas) => {
  const doc1Page = await doc1.getPage(index + 1);
  const doc2Page = await doc2.getPage(index + 1);
  const doc1Box = await doc1Page.getCropBox();
  const doc2Box = await doc2Page.getCropBox();

  const ctx = canvas.getContext('2d');
  ctx.strokeStyle = '...';
  ctx.strokeRect(doc1Box.x1, doc1Box.y1, doc1Box.x2 - doc1Box.x1, doc1Box.y2 - doc1Box.y1);
  ctx.strokeStyle = '...';
  ctx.strokeRect(doc2Box.x1, doc2Box.y1, doc2Box.x2 - doc2Box.x1, doc2Box.y2 - doc2Box.y1);
});
```

I'm not sure how you implement the diff mode but another option you can choose is that after a user exits the diff mode you can iterate through all the annotations in the document, check if their [rects](https://www.pdftron.com/api/web/Annotations.Annotation.html#getRect__anchor) are within the page box. If it's not then you can use [fitTo](https://www.pdftron.com/api/web/Annotations.Rect.html#fitTo__anchor) to make the rect stay in the box.

Let me know how this works and if you have any other questions. Again, sorry for the delay in the response and have a nice day!

Alternatively after exit the diff mode

**Comment by ZhijieZhang** [comment]
Okay! Here is what I found, hopefully it's helpful.

I'm assuming you are using the `appendVisualDiff` API with full api so I'm going to refer to the [this sample](https://www.pdftron.com/samples/web/samples/full-apis/ViewerPDFDiffTest/) which uses this API.

After we finish creating the diff document and before we call loadDocument with the `newDoc` we can listen to the `pageComplete` event and then in the event handler we can grab the page canvas, and use `ctx.strokeRect` to draw the boundaries of the documents. You can get the boundaries using the [getCropBox](https://www.pdftron.com/api/web/PDFNet.Page.html#getCropBox__anchor) API. The code would look like this:

```javascript
readerControl.docViewer.off('pageComplete.viewerDiff');
readerControl.docViewer.on('pageComplete.viewerDiff', async(index, canvas) => {
  const doc1Page = await doc1.getPage(index + 1);
  const doc2Page = await doc2.getPage(index + 1);
  const doc1Box = await doc1Page.getCropBox();
  const doc2Box = await doc2Page.getCropBox();

  const ctx = canvas.getContext('2d');
  ctx.strokeStyle = '...';
  ctx.strokeRect(doc1Box.x1, doc1Box.y1, doc1Box.x2 - doc1Box.x1, doc1Box.y2 - doc1Box.y1);
  ctx.strokeStyle = '...';
  ctx.strokeRect(doc2Box.x1, doc2Box.y1, doc2Box.x2 - doc2Box.x1, doc2Box.y2 - doc2Box.y1);
});
```

I'm not sure how you implement the diff mode but another option you can choose is that after a user exits the diff mode you can iterate through all the annotations in the document, check if their [rects](https://www.pdftron.com/api/web/Annotations.Annotation.html#getRect__anchor) are within the page box. If it's not then you can use [fitTo](https://www.pdftron.com/api/web/Annotations.Rect.html#fitTo__anchor) to make the rect stay in the box.

Let me know how this works and if you have any other questions. Again, sorry for the delay in the response and have a nice day!

Alternatively after exit the diff mode

**Comment by ZhijieZhang** [comment]
Hi,

I'm going to close this issue as I didn't hear back from you for a while. Please feel free to reopen this issue and discuss further if you want to. Thanks and have a nice day!
