### ISSUE TITLE
Error when installing inside Docker build environment

### ISSUE THREAD

**Issue by samuellaycock** [PDFTron/webviewer-ui#499]
When running `npm install` from within a Dockerfile, the process fails every time at the same point. It seems to be a problem with how webviewer relies on https://github.com/lbittner-pdftron/extract-zip.git.

Stacktrace:
```
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t https://github.com/lbittner-pdftron/extract-zip.git
npm ERR! enoent 
npm ERR! enoent 
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
```

That `undefined` above is the likely the culprit I would imagine?

The current node Docker image we're using is `node:12-alpine`, but we've tried `node:12-buster-slim` and `node:10-*` for both linux flavours and get the same error each time.

**Comment by ZhijieZhang** [comment]
Hi,

We forked a repo that `@pdftron/webviewer-downloader` is using to try fixing https://github.com/PDFTron/webviewer-ui/issues/487. The forked repo will be installed from git when installing the `webviewer-downloader` package. It looks like your container doesn't have git installed. Can you try installing git and see if the issue can be resolved?

**Comment by samuellaycock** [comment]
Ah, of course,  that makes sense! Thanks, I'll take a look and get back to you.

**Comment by samuellaycock** [comment]
Yes, this was the problem. Thanks again.
