### ISSUE TITLE
API for rightPanel 

### ISSUE THREAD

**Issue by tiimoS** [PDFTron/webviewer-ui#503]
Hi, 
we are trying to add a right-side panel in the viewer. The right-side panel should look and behave similar to the already existing leftPanel. However, I do not seem to find any api that would allow to set a right-side panel. There is some sort of api for setActiveLeftPanel, but no option to enable a right-side panel. 
Instead we have now used a normal ng-sidebar, which is pushed in upon a toolbutton click in the header. However, the sidebar pushes the whole web-viewer content. For consistency, the two side-panels should behave similarly, so the header should be sticky and the panel should only push the content below the header. Is there any way we can achieve the addition of a rightPanel with the existing features? 

Thanks for the quick support and efforts!

**Comment by ZhijieZhang** [comment]
Hi,

Thanks for contacting us regarding WebViewer!

Unfortunately there're no APIs for adding a right panel to the viewer now, but this is on our roadmap. The main thing for us to think about before adding this API is if there will be any interaction conflicts between the existing search panel(which pushed in from right) and the custom right panels.

We plan to roll out a new UI design in the next few months, and in the new design we've moved the notes panel to the right side of the viewer. Would it be okay to add an API to add a right panel after the new UI is out?

It'd be easier to for you to achieve this requirement by modifying the UI source code for now. You would need to modify `initialState.js` to add a button to the header to toggle the right panel, and add a `<RightPanel />` to `App.js`. I can push a branch to origin that provide you with the base to modify. Just let me know if you want this or you're fine waiting for an API to be implemented.

**Comment by tiimoS** [comment]
Thanks for the feedback. I'm happy to see that a change is coming in the native viewer. I will check internally if we can await the changes and get back to you in case I have problems with your proposed changes ;)
