### ISSUE TITLE
[Question] Switch between Full and Standard API dynamically?

### ISSUE THREAD

**Issue by henry-chris** [PDFTron/webviewer-ui#505]
After testing it seems that loading documents using the Full API is about .5s - 2.5s slower for our test documents.  

We have built a custom document compare UI for comparing versions of documents.  I'd like to be able to load normally in the standard UI since 85% of our use cases will be standard document sessions.

When the user hits the comparison button I'd like to then load the Full API without having to re-instantiate a new Webviewer instance.  

Is this possible with the way the UI is set up?

**Comment by ZhijieZhang** [comment]
it is possible to load Full API dynamically after WebViewer is initialized with the standard API, though it takes a few steps.

The code will look like this:
```javascript
loadFullAPI: async() => {
  await loadScript('../core/pdf/PDFNet.js');

  const { CoreControls, PDFNet } = instance;
  CoreControls.resetWorker();
  const backendType = await CoreControls.getDefaultBackendType();

  CoreControls.enableFullPDF(true);
  CoreControls.initPDFWorkerTransports(backendType, { l: 'your_license_key_here' });

  await PDFNet.initialize();
},
```

The `loadScript` function basically just creates a `<script>` with `PDFNet.js` being the source. 

Note that operations like [rotating](https://www.pdftron.com/api/web/CoreControls.Document.html#rotatePages__anchor), inserting, deleting, etc should be disallowed until the transition to Full API is completed. Currently it's really difficult to maintain the edit state while switching between different workers. In longer term we hope that we can investigate a more on-demand approach to loading the Full API(workers).

**Comment by henry-chris** [comment]
Great thanks.  Yes I saw the loadScript happening in index.js but wasn't sure I could do it dynamically without messing stuff up.

Appreciate the help.
