### ISSUE TITLE
Document Compare Rotation for some landscape PDFs

### ISSUE THREAD

**Issue by henry-chris** [PDFTron/webviewer-ui#509]
1. Initiate Document Compare with 2 landscape PDFs (wider than taller).
2. When comparison document is finished, the pdf will be rotated to portrait mode and the PDF text will be sideways.

**Comment by ZhijieZhang** [comment]
Sorry for the daly in the reply! I'm going to try to reproduce the issue on my end and get back to you once I have more information.

**Comment by ZhijieZhang** [comment]
Hi Chris,

Sorry for the delay in the reply. I'm able to reproduce the issue using the [ViewerPDFDiffTest sample](https://www.pdftron.com/samples/web/samples/full-apis/ViewerPDFDiffTest/).

I'm going to talk to my colleague who's more familiar with the [appendVisualDiff](https://www.pdftron.com/api/web/PDFNet.PDFDoc.html#appendVisualDiff__anchor) API. In the meanwhile, I found a workaround for this issue. It isn't perfect as it will increase the time between appending the diffing pages and loading the document. The workaround keeps track of original page rotations, and use the `rotatePages` API to make sure the rotation stays the same for the new document.

```javascript
const compareDoc = async(doc1, doc2) => {
  const newDoc = await PDFNet.PDFDoc.create();
  newDoc.lock();

  const options = await getDiffOptions();

  const pages = [];
  const rotations = [];
  const itr = await doc1.getPageIterator(1);
  const itr2 = await doc2.getPageIterator(1);

  let i = 0;
  for (itr; await itr.hasNext(); itr.next()) {
    const page = await itr.current();
    pages[i] = [page];
    rotations[i] = [await page.getRotation()];
    i++;
  }

  i = 0;
  for (itr2; await itr2.hasNext(); itr2.next()) {
    const page = await itr2.current();
    (pages[i] || (pages[i] = [null])).push(page);
    (rotations[i] || (rotations[i] = [null])).push(await page.getRotation());
    i++;
  }

  pages.forEach(async([p1, p2]) => {
    if (!p1) {
      p1 = new PDFNet.Page(0);
    }
    if (!p2) {
      p2 = new PDFNet.Page(0);
    }

    await newDoc.appendVisualDiff(p1, p2, options);
  });

  await newDoc.unlock();

  const doc = await CoreControls.createDocument(newDoc);
  for (let i = 0; i < rotations.length; i++) {
    const [p1Rotation, p2Rotation] = rotations[i];
    const rotation = p1Rotation || p2Rotation;

    await doc.rotatePages([i + 1], rotation);
  }

  const rotatedDocData = await doc.getFileData({ downloadType: 'pdf' });
  readerControl.loadDocument(new Blob([new Uint8Array(rotatedDocData)], { type: 'application/pdf' }));
};
```

**Comment by ZhijieZhang** [comment]
I'm closing this issue for now as there're no recently activities, and it's more of a Core issue rather than UI. If this is still an issue for you, please open a ticket via https://www.pdftron.com/form/request/
