### ISSUE TITLE
Callout annotation broken when it's a single line

### ISSUE THREAD

**Issue by henry-chris** [PDFTron/webviewer-ui#52]
Version 4.0.2.68331 of Webviewer
In Chrome

Only seems to break when creating a callout with a single line:
1. Select callout annotation tool
2. Click on a document to start annotation
3. Double click somewhere on the document to end the annotation.
5. No text box appears, cannot select callout, callout disappears and is not saved/exported.

**Comment by justinjung04** [comment]
Thank you for the report. I was able to reproduce the issue by start drawing callout annotation and click somewhere outside of the page to get it in a bad state. We will investigate and come up with a fix.

**Comment by justinjung04** [comment]
The fix has been added to the following custom build:
https://www.pdftron.com/ID-zJWLuhTffd3c/WebViewer/WebViewer_4.0.3.68694.zip
This will be included in future release.

**Comment by henry-chris** [comment]
I'd like to open this back up.

We just tested this after merging in the new version.

1. You are successfully cancelling the annotation if there is only one line when a user:
    a. Clicks off the document
    b. Double clicks
2. You are still bugging out the annotation when:
    a. The user right clicks to end the annotation.
3. Do you not want to allow single line callouts?  I know that Adobe allows them as I just tested it.  I'm not sure what other software does.  It seems like a hassle to _need_ to create a 2nd line for a callout if needed...but that's just me.

**Comment by justinjung04** [comment]
Fix has been implemented in CoreControls: https://drive.google.com/file/d/1w1nBeAgMiERRECjii7Px-mzwxHPijxud/view?usp=sharing
This will be included in future release as well.
