### ISSUE TITLE
PDFNet API CreateFromURL doesn't accept multiple args

### ISSUE THREAD

**Issue by henry-chris** [PDFTron/webviewer-ui#521]
May need to be somewhere else.  Let me know and I can close.

Issue in V5.8.xxx  of PDFNet - 

Can't send custom headers in `CreateFromURL()`.
Docs for `CreateFromURL()` say signature is   `CreateFromURL(url [,options])`.  However, there is a guard statement that precludes more than 1 argument to the method.

It's also not apparent that you can send custom headers, though it _seems_ like you can after looking at code and changing the argument check.

**Comment by ZhijieZhang** [comment]
It seems that this issue is fixed in 6.1. I'm going to ask my colleague to see if we can back merge this change to 5.2.x. Sorry for the inconvenience!

**Comment by ZhijieZhang** [comment]
We've made a fix internally, and it will be available in today's nightly build. Can you try the build tomorrow and let me know if you still encounter the same issue? You can download the build here https://www.pdftron.com/nightly/#stable/.

**Comment by henry-chris** [comment]
The 5.2.9 version seemed to work. 

I'm trying out 6.1, also, and it seems that your builds no longer give the UI source in the nightlies.  Is that now only avaliable from github? 

If so, how do we figure out exactly which source was used to test the build?

**Comment by ZhijieZhang** [comment]
Sorry for the delay in the response!

> Is that now only available from github?
Yes, we removed the source code as it's available in this repo already, and also to keep the size of the download package smaller than before.

> If so, how do we figure out exactly which source was used to test the build?
Do you mean the UI version? The exact UI version can be checked in `package.json`.

https://github.com/PDFTron/webviewer-ui/blob/d6bffb14b813a3d9aeb52bf13b4b911fd1617dfc/package.json#L3-L5

We also console log the version of WebViewer and WebViewer UI in the console, so when you are testing the build you can check the console.

https://github.com/PDFTron/webviewer-ui/blob/d6bffb14b813a3d9aeb52bf13b4b911fd1617dfc/src/helpers/logDebugInfo.js#L22-L29

Let me know if this is what you are looking for and if you have other questions!

**Comment by henry-chris** [comment]
Ok, so you can only get the build information at runtime or looking through the CoreControls file.  I guess that works.
