### ISSUE TITLE
Subzero always enabled even if 'ems' passed

### ISSUE THREAD

**Issue by henry-chris** [PDFTron/webviewer-ui#537]
Version 6.1.1
Chrome Browser v80+

EDIT:  Ok, i'm just going to put down stuff I'm noticing as I debug through this:
1. PDFNet.initialize is not documented and in your samples it doesn't show that there is a second parameter (pdfBackendType).
2. In PDFNet.initialize you check for readerControl.pdfType.  This...doesn't seem to exist on readerControl anymore as far as I can tell.  It seems to be mapped directly to pdfBackendType.
3. subZero being true/false doesn't seem to matter at all when instantiating webviewer from my pov.

--- Original ---
From what I can tell in webviewer.js (You no longer seem to give the unminified version in nightly builds so it's more difficult to parse) the 'subzero' property is set to 'true' by default and there is no option to disable it.  So, the '&subzero=1' is always sent which seems to make initialization attempt to load with PNACL (which won't work anymore I think).

This is a problem I found when attempting to debug another problem (which is probably better in a private ticket).  Basically, there is a list of PDFNet features available in PDFWorker.js via a map.  I'm attempting to use 'pdfDocCreateFromBuffer' to diff files and it works in development.  Yet, when I deploy I see that 'Module._TRN_EMSCreatePDFNetWorkerInstance' is never created properly and thus those message types are never added to the map.  

Currently trying to figure that out...should I put that issue here or would you like it somewhere else?

**Comment by ZhijieZhang** [comment]
The `subzero` option is mainly for Chrome PNaCl, which has been deprecated by the Chrome team now. So this option isn't really useful at this point.

> always sent which seems to make initialization attempt to load with PNACL (which won't work anymore I think).
You could use `backendType: 'ems'` to let WebViewer not load PNaCl modules. [This FAQ ](url)might be helpful. https://www.pdftron.com/documentation/web/faq/pnacl-modules/#hide-the-error

> PDFNet.initialize
That's a good catch. It seems that we didn't document this API at all, and the implementation regarding readerControl seems to be related only to the legacy UI. I will talk to the team and have this fixed.

> Basically, there is a list of PDFNet features available in PDFWorker.js via a map. I'm attempting to use 'pdfDocCreateFromBuffer'
I'm not very clear about what the issue is unfortunately. If you use `backendType: 'ems'`, does this issue get fixed? If the issue contains some code that you don't want to share in public, feel free to open a ticket :)

Let me know how the above works, and if you have any other questions.

**Comment by henry-chris** [comment]
I've been passing `backendType: 'ems'` the entire time.  You can see that your Demo site also tries to use PNACL at first.

The only thing that helps this is adding `readerControl.pdfType: 'ems'` in `apis/index.js`.  After doing this the error went away.  

However that's only something I found in my search to solve the core problem of the PDFWorker.js not initializing properly.  I did start passing `'ems'` as the second option to `PDFNet.initialize()` and still see the same problem. 

Your demo site works fine, so I'm still searching for the answer.  I think this covers all the problems I've found when implementing this as the UI level, so feel free to close it if you are handling all the API and readercontrol stuff.

**Comment by ZhijieZhang** [comment]
> I did start passing 'ems' as the second option to PDFNet.initialize() and still see the same problem.
I looked at the code, and it seems that passing `ems` as the second argument to it should have the same effect as setting `readerControl.pdfType` to `ems` in the UI. Can you show me an example where passing `ems` when calling `initialize` still errors out?

**Comment by henry-chris** [comment]
It seems part of this problem was from my end.  We use a service worker and were not saving query strings within our cache.  The `CoreControls `file being loaded thought it was `'full api'` while the `PDFWorker.js` file was `'lean api'` because the query string for the full api was not being used.  

This seems to have just happened after upgraded to 6.X over 5.2.8.  Even though we haven't been caching query strings for 6 months.

I created a ticket in your system but then closed it as I found the problem the same day.  I forgot to comment here, also.

However, let me clear a couple things up.

The main `'ems'` problem I found was from the Webviewer constructor.  Even if passed there, Chrome still tried to load PNACL or at least threw the error to the console.  When I had no idea of my issue, this was my 'start from scratch'.  I was trying to figure out everything related to loading full vs lean api and this was a single stepping stone.

It seems that after fixing the query string issue in my service worker the same problems _do not exist_.

If I pass 'ems' in the WV constructor now it doesn't throw the PNACL error as it used to.  I took out the `'pdfType: 'ems''` from the `readerControl `object also.  Everything seems to work OK now.

Closing this, but if you can add the documentation for `PDFNet.initialize()` I'm sure it will be helpful to others.

Honestly, my apologies for causing you all more work for a silly error on my end.
