### ISSUE TITLE
Provide Italian translations

### ISSUE THREAD

**Issue by peterpeterparker** [PDFTron/webviewer-ui#550]
## Feature Requests

Please provide **Italian** translations in your [i18n](https://github.com/PDFTron/webviewer-ui/tree/6.2/i18n) support.

This is notably a must for our application as we operate in a multi-language country, Switzerland.

Thx in advance
David

**Comment by ZhijieZhang** [comment]
Hi,

Thanks for bringing this up. 

Most of the translations in this repo are human translated(for example, https://github.com/PDFTron/webviewer-ui/pull/114), with some of the newly added strings are translated using machine.

We don't have any Italian speakers on the team, so if you could provide us with a translation file that'd be great. If you are going to do this, you can fork the repo and make a PR to this upstream.

If it's okay to you I can also use google translation API to automatically generate Italian translations. We have the script to do this, which only takes a few seconds.

Please let me know which approach you'd want to take. Thanks!

**Comment by peterpeterparker** [comment]
Unfortunately I can't provide these as I don't speak Italian good enough.

Hopefully some day someone will provide these or alternatively one of your client will requests these.

**Comment by ZhijieZhang** [comment]
I've added a Italian translation in this commit https://github.com/PDFTron/webviewer-ui/commit/05e6e442ded9280707d2b91717127ffe719fd33d.

Currently the change is only in the master branch, which means it will be available in the next minor version release.

If you'd like it to be picked to version 6.2.x, please let me know! :)

**Comment by peterpeterparker** [comment]
Thank you for the PR.

But to be honest with you, I'm not a big fan of using Google Translation to provide translations for applications, at least without a serious review afterwards as often they contain mistakes or don't make sense in the context.

Following your message, for example, I had a look to the French translations. It looks like they were generated with you Google Translation too because I already noticed mistakes within the first translations in the file.

**Comment by ZhijieZhang** [comment]
Thanks for the feedback!

When the first version of WebViewer UI is released, all the translations are done through a paid service, so they are reviewed and the quality can be ensured to some extent. With new features being implemented, this file now contains Google translated strings(roughly 40%). If you noticed that some translations are awkward, we'd appreciate if you could make a PR to correct them.

I can't say how the quality for the Italian translation is, but as a native Chinese speaker I would say that the translation done by Google Translation API in the Chinese i18n file are not always perfectly accurate given the context, but can be easily understood by other native speakers. So I think it's acceptable and usable.

If you'd want to have more control over the quality of the Italian translation, we encourage you to do the translation on your end, and then make a PR to add it in this repo.

**Comment by ZhijieZhang** [comment]
Closing this issue as the Italian translation is merged into master and will be available in the next release.

However, as stated above, you are welcomed to do the translation on your end and provide a more accurate one to replace the existing one.

Have a nice day!
