### ISSUE TITLE
Additional style menu not visible in iPhone and Ipad?

### ISSUE THREAD

**Issue by henry-chris** [PDFTron/webviewer-ui#560]
iOS v13.2.2
WV: 6.2.2
Repro - 
* Open any item in PDF markups in Landscape mode
* Click on any Issue or Annotation on the page
* Additional buttons appears and click on 'Style' button

Result: additional Style menu appears but part of it is not visible on the screen. 

Here is a terrible screenshot of a video...sorry.

![image](https://user-images.githubusercontent.com/4165721/78619263-7982a080-7842-11ea-832f-f1f8a7c0623b.png)

**Comment by ZhijieZhang** [comment]
This issue should be fixed in the latest nightly build at https://www.pdftron.com/nightly/#stable/2020-04-16/

Can you give it a try and see how it goes?
