### ISSUE TITLE
instance.Feature is undefined

### ISSUE THREAD

**Issue by BrandonMathis** [PDFTron/webviewer-ui#562]
Hi PDFTron Team!

I am in the process of configuring my webviewer to have some features disabled depending on misc criteria. I found in your documentation a methodology to disable a set of features for an instance of the WebViewer but it seems that `Features` is undefined on `instance`.

So, instead of disabling features like this

```js
WebViewer(...)
  .then(function(instance) {
    var Feature = instance.Feature;
    instance.disableFeatures([Feature.Download]);
  });
```

I have to do

```js
WebViewer(...)
  .then(function(instance) {
    instance.disableDownload();
  });
```

Is there perhaps an error in the documentation or an error in how I am calling for the `Features` object? Any help is appreciated.

**Comment by ZhijieZhang** [comment]
Hi there,

Thanks for contacting us regarding WebViewer!

Could you let us know the version of WebViewer you are using? `instance.Feature` is added in `6.0`, so if you are using an older version it will be `undefined`. In older versions `instance.disableDownlolad`, `instance.disablePrint` are the correct ways to disable the features you don't want to have.

**Comment by ZhijieZhang** [comment]
I'm going to close this issue because I believe that this is not an issue in WebViewer 6.0+ versions. You are doing correctly by using `disableDownload` in older version. Let me know if you have any other questions!
