### ISSUE TITLE
[BUG] Cannot backspace text in Firefox

### ISSUE THREAD

**Issue by henry-chris** [PDFTron/webviewer-ui#566]
Demo Viewer.  Found in V6.2.2.

Open firefox
Go to demo
Create annotation
Type comment in panel
Attempt to backspace text

Looking for direct cause now.

**Comment by ZhijieZhang** [comment]
Thanks for bringing this up!

This issue is actually in WebViewer, not the UI. We've just recently fixed it and the fix is available in the nightly build. Can you try the latest nightly build and check if it's working now? https://www.pdftron.com/nightly/#stable/2020-04-13/

**Comment by henry-chris** [comment]
Confirmed working.
