### ISSUE TITLE
Possibility to Drag & Drop Annotations

### ISSUE THREAD

**Issue by tiimoS** [PDFTron/webviewer-ui#568]
Is there the possibility to add d&d functionality to annotated text sources ? Anything planned here? We have the viewer embedded with an additional side-panel and would like to drag and drop annotations into this side-panel. 

Thanks for a quick feedback

**Comment by ZhijieZhang** [comment]
Hi, could you clarify a bit more about `annotated text sources`? Does this mean text annotations such as highlight, underline, etc?

Also, you are wanting to drag an annotation that's in the WebViewer iframe, to the side panel that's in your app(in the parent window), or the other way around?

We have a sample [here](https://www.pdftron.com/samples/web/samples/forms/form-builder/) that allows you to d&d to create an annotation inside WebViewer. If you click the link, there's an blur `Add field` button in the left bottom. And if you drag and drop it in WebViewer a freetext annotation will be added. Not sure if this is what you are looking for?

**Comment by tiimoS** [comment]
Thanks for the sample. However, our case is slightly different. 
In our use case, one would e.g. highlight a text source to create the annotation. Then the user would click on the annotated text to select it and move it to a side panel outside the webviewer iframe , ie. in the parent window, to create the field there.

**Comment by ZhijieZhang** [comment]
Thanks for the elaboration.

![gif](https://user-images.githubusercontent.com/25110092/80240022-118bd280-8616-11ea-9517-ba37c57befa5.gif)

Is this what you are looking for? I was able to achieve it by using the following code:
```javascript
WebViewer(
  {
    path: '../../../lib',
    initialDoc: 'https://pdftron.s3.amazonaws.com/downloads/pl/demo-annotated.pdf',
  },
  document.getElementById('viewer')
).then(instance => {
  const { annotManager, Annotations, iframeWindow } = instance;

  const div = document.querySelector('#div1');
  div.addEventListener('drop', (e) => {
    e.preventDefault();

    div.textContent = e.dataTransfer.getData('contents');
  })
  div.addEventListener('dragover', e => {
    e.preventDefault();
  })

  annotManager.on('annotationSelected', (annotations, action) => {
    if (action === 'selected' && annotations.length === 1) {
      const annot = annotations[0];

      if (!(annot instanceof Annotations.TextHighlightAnnotation)) {
        return;
      }

      const pageIndex = annot.PageNumber - 1;
      const containerEle = iframeWindow.document.querySelector(`#pageWidgetContainer${pageIndex}`);
      containerEle.draggable = true;
      containerEle.addEventListener('dragstart', (e) => {
        e.dataTransfer.setData('contents', annot.getContents());
      })
    }
  })
});
```
The code is certainly not complete, but should show a direction to try.
I need to talk to the team to discuss about this feature, but this is the first time I've seen this request so we might end up not making this built in. However, if there're more similar sounding requests like this we will definitely discuss about it again.

**Comment by tiimoS** [comment]
Thanks a lot! This should do the trick :)
