### ISSUE TITLE
Unable to specify Opacity when creating 'Highlight' from tool

### ISSUE THREAD

**Issue by henry-chris** [PDFTron/webviewer-ui#569]
![image](https://user-images.githubusercontent.com/4165721/79390004-8daa5a00-7f34-11ea-841a-4b21c91019c7.png)

Should add opacity option here.  Option exists on AnnotationPopup after creation.

**Comment by ZhijieZhang** [comment]
Thanks for bringing this up. It looks like we didn't enable the default opacity style in WebViewer. I just opened a PR to fix it in the private WebViewer repo.

Once it goes through, you should see it in the nightly build. :)
