### ISSUE TITLE
Highlight hover effect exists while creating Signature

### ISSUE THREAD

**Issue by henry-chris** [PDFTron/webviewer-ui#570]
If you highlight text and then attempt to create a signature then the hover effect still fires.  Users have pointed out that it's distracting.

Note, may exist in other modal/popup situations.

![image](https://user-images.githubusercontent.com/4165721/79394341-d6fea780-7f3c-11ea-8045-b113ee4d9354.png)

**Comment by ZhijieZhang** [comment]
Thanks for bringing this up. I've opened a PR to fix this issue.

Once it goes through you can use the nightly build, which should contain this fix.

**Comment by achenPDFTron** [comment]
Note to self, able to replicate the bug on https://www.pdftron.com/samples/web/samples/viewing/viewing/
