### ISSUE TITLE
Stateful button image does not update in Safari, IE11

### ISSUE THREAD

**Issue by daneverso** [PDFTron/webviewer-ui#592]
I have a stateful button configured like this:

```
    {
      // Full screen stateful button
      type: 'statefulButton',
      initialState: 'NotFullScreen',
      dataElement: 'datasiteFullScreenButton',
      states: {
        FullScreen: {
          title: translations.action.exitFullscreen,
          img: '../ui/assets/mrll_exit_fs.svg',
          onClick: () => {
            instance.toggleFullScreen();
          },
        },
        NotFullScreen: {
          title: translations.action.enterFullscreen,
          img: '../ui/assets/mrll_enter_fs.svg',
          onClick: () => {
            instance.toggleFullScreen();
          },
        },
      },
      mount: update => {
        const fullScreenToState = isFullScreen => {
          if (isFullScreen) {
            return 'FullScreen';
          } else {
            return 'NotFullScreen';
          }
        };
        document.addEventListener('fullscreenchange', () => {
          let isFullScreen = false;
          let doc: any = window.document;
          if (
            doc.fullscreenElement ||
            doc.mozFullScreenElement ||
            doc.webkitFullscreenElement ||
            doc.msFullscreenElement
          ) {
            isFullScreen = true;
          }
          update(fullScreenToState(isFullScreen));
        });
      },
      unmount: () => {
        document.removeEventListener('fullscreenchange', () => {});
      },
      hidden: ['mobile'],
    }
```
In Chrome, Firefox and Edge the button images update on click.
In Safari and IE11 they do not.

**Comment by daneverso** [comment]
mrll_exit_fs.svg:

<svg width="21px" height="22px" viewBox="0 0 21 22" version="1.1" xmlns="http://www.w3.org/2000/svg"><path d="M17.3905835,9.8125219 C18.2683318,9.8125219 18.7071659,8.75020373 18.0878475,8.13088529 L16.7343351,6.85940395 L20.8071689,2.7865701 C21.0614732,2.53226582 21.0614732,2.11389944 20.8071689,1.85959516 L19.7653986,0.817824798 C19.5110943,0.563520519 19.0927279,0.563520519 18.8384236,0.817824798 L14.7655898,4.89065864 L13.4900229,3.53714624 C12.8706644,2.9178278 11.8124718,3.3566619 11.8124718,4.2344102 L11.8124718,8.82814925 C11.8124718,9.37364775 12.251346,9.8125219 12.7968445,9.8125219 L17.3905835,9.8125219 Z M8.20310544,9.8125219 C8.74860394,9.8125219 9.1874781,9.37364775 9.1874781,8.82814925 L9.1874781,4.2344102 C9.1874781,3.36078749 8.12515992,2.92191333 7.50584148,3.54123177 L6.23436014,4.89065864
L2.16152629,0.817824798 C1.90722202,0.563520519 1.48885563,0.563520519 1.23455135,0.817824798 L0.192780989,1.85959516 C-0.0615232908,2.11389944 -0.0615232908,2.53226582 0.192780989,2.7865701 L4.26561483,6.85940395 L2.91210243,8.13497082 C2.29278399,8.75432931 2.73161809,9.8125219 3.60936639,9.8125219 L8.20310544,9.8125219 Z M2.16152629,21.4322128 L6.23436014,17.3593789 L7.50992701,18.7128913 C8.1292855,19.3322097 9.1874781,18.8933757 9.1874781,18.0156273 L9.1874781,13.4218883 C9.1874781,12.8763898 8.74860394,12.4375156 8.20310544,12.4375156 L3.60936639,12.4375156 C2.73161809,12.4375156 2.29278399,13.4957082 2.91210243,14.1191523 L4.2615293,15.3906336 L0.192780989,19.4634674 C-0.0615232908,19.7177717 -0.0615232908,20.1361381 0.192780989,20.3904424 L1.23455135,21.4322128 C1.48885563,21.686517 1.90722202,21.686517 2.16152629,21.4322128 Z M19.7653986,21.4363383 L20.8071689,20.3945279 C21.0614732,20.1402236 21.0614732,19.7218573 20.8071689,19.467593 L16.7343351,15.3906336 L18.0878475,14.1150667 C18.7071659,13.4957082 18.2683318,12.4375156 17.3905835,12.4375156 L12.7968445,12.4375156 C12.251346,12.4375156 11.8124718,12.8763898 11.8124718,13.4218883 L11.8124718,18.0156273 C11.8124718,18.8933757 12.87479,19.3322097 13.4941085,18.7128913 L14.7655898,17.3634644 L18.8384236,21.4363383 C19.0927279,21.6906026 19.5110943,21.6906026 19.7653986,21.4363383 Z" id="exit" fill="#757575" fill-rule="nonzero"></path></svg>

mrll_enter_fs.svg:

<svg width="19px" height="20px" viewBox="0 0 19 20" version="1.1" xmlns="http://www.w3.org/2000/svg"><path d="M5.5781117,19.3124969 C6.45541941,19.3124969 6.89429356,18.2501787 6.27537566,17.6308603 L4.78936389,16.1502157 L9.1874781,11.7492176 L13.5843506,16.1460902 L12.0995805,17.6308603 C11.4806626,18.2501787 11.9195368,19.3124969 12.7968445,19.3124969
L17.3930669,19.3124969 C17.9350807,19.3124969 18.3749562,18.8726214 18.3749562,18.3306076 L18.3749562,13.7343852 C18.3749562,12.8566369 17.312638,12.4178028 16.6933196,13.0412067 L15.2093906,14.5259768 L10.8092336,10.1250188 L15.20895,5.72814625 L16.6933196,7.21291634 C17.3130786,7.83223478 18.3749562,7.39340068 18.3749562,6.51565238 L18.3749562,1.91942997 C18.3749562,1.37741619 17.9350807,0.93754068 17.3930669,0.93754068 L12.7968445,0.93754068 C11.9195368,0.93754068 11.4806626,1.99985886 12.0995805,2.6191773 L13.5855923,4.09982181 L9.1874781,8.50081992 L4.79060557,4.10394739 L6.27537566,2.6191773 C6.89429356,1.99985886 6.45541941,0.93754068 5.5781117,0.93754068 L0.981889291,0.93754068 C0.439875508,0.93754068 0,1.37741619 0,1.91942997 L0,6.51565238 C0,7.39340068 1.06231818,7.83223478 1.68163662,7.21291634 L3.16556557,5.72406072 L7.56572255,10.1250188 L3.16600617,14.5218913 L1.68163662,13.0371212 C1.06187758,12.4178028 0,12.8566369 0,13.7343852 L0,18.3306076 C0,18.8726214 0.439875508,19.3124969 0.981889291,19.3124969 L5.5781117,19.3124969 Z" id="enter" fill="#757575" fill-rule="nonzero"></path></svg>

**Comment by daneverso** [comment]
`<svg width="19px" height="20px" viewBox="0 0 19 20" version="1.1" xmlns="http://www.w3.org/2000/svg"><path d="M5.5781117,19.3124969 C6.45541941,19.3124969 6.89429356,18.2501787 6.27537566,17.6308603 L4.78936389,16.1502157 L9.1874781,11.7492176 L13.5843506,16.1460902 L12.0995805,17.6308603 C11.4806626,18.2501787 11.9195368,19.3124969 12.7968445,19.3124969
L17.3930669,19.3124969 C17.9350807,19.3124969 18.3749562,18.8726214 18.3749562,18.3306076 L18.3749562,13.7343852 C18.3749562,12.8566369 17.312638,12.4178028 16.6933196,13.0412067 L15.2093906,14.5259768 L10.8092336,10.1250188 L15.20895,5.72814625 L16.6933196,7.21291634 C17.3130786,7.83223478 18.3749562,7.39340068 18.3749562,6.51565238 L18.3749562,1.91942997 C18.3749562,1.37741619 17.9350807,0.93754068 17.3930669,0.93754068 L12.7968445,0.93754068 C11.9195368,0.93754068 11.4806626,1.99985886 12.0995805,2.6191773 L13.5855923,4.09982181 L9.1874781,8.50081992 L4.79060557,4.10394739 L6.27537566,2.6191773 C6.89429356,1.99985886 6.45541941,0.93754068 5.5781117,0.93754068 L0.981889291,0.93754068 C0.439875508,0.93754068 0,1.37741619 0,1.91942997 L0,6.51565238 C0,7.39340068 1.06231818,7.83223478 1.68163662,7.21291634 L3.16556557,5.72406072 L7.56572255,10.1250188 L3.16600617,14.5218913 L1.68163662,13.0371212 C1.06187758,12.4178028 0,12.8566369 0,13.7343852 L0,18.3306076 C0,18.8726214 0.439875508,19.3124969 0.981889291,19.3124969 L5.5781117,19.3124969 Z" id="enter" fill="#757575" fill-rule="nonzero"></path></svg>
`

**Comment by daneverso** [comment]
Sorry, I see the problem now.

**Comment by ZhijieZhang** [comment]
Hi Dan,

It seems that to listen to the fullscreen change event in Safari and IE, we need to specifically listen to `webkitfullscreenchange` and `MSFullscreenChange`. The code below should resolve the issue you are having:

```javascript
mount: update => {
  const fullScreenToState = isFullScreen => {
    if (isFullScreen) {
      return 'FullScreen';
    } else {
      return 'NotFullScreen';
    }
  };
  const handleFullScreenChange = () => {
    let isFullScreen = false;
    const doc = window.document;
    if (
      doc.fullscreenElement ||
      doc.mozFullScreenElement ||
      doc.webkitFullscreenElement ||
      doc.msFullscreenElement
    ) {
      isFullScreen = true;
    }
    update(fullScreenToState(isFullScreen));
  };
  document.addEventListener('fullscreenchange', handleFullScreenChange);
  // for Firefox, but might not be necessary anymore
  document.addEventListener('mozfullscreenchange', handleFullScreenChange);
  document.addEventListener('webkitfullscreenchange', handleFullScreenChange);
  document.addEventListener('MSFullscreenChange', handleFullScreenChange);
},
```

**Comment by daneverso** [comment]
Thanks Zhijie, that works.

**Comment by daneverso** [comment]
Yes Zhijie that was the issue – I’m a little embarrassed I didn’t look further before bothering you.

We are busy getting ready to go live. I think I have another ticket or two out there, will answer those as soon as I know more.

Thanks again for all your help!
Dan

Dan Everson
Senior Software Engineer

733 Marquette Ave., Suite 600
Minneapolis, MN 55402
dan.everson@datasite.com<mailto:dan.everson@datasite.com>
datasite.com<http://www.datasite.com/>

[signature_1815713617]<https://www.datasite.com/>

**Comment by ZhijieZhang** [comment]
No worries at all! I'm glad that I helped resolve the issue.
