### ISSUE TITLE
Expose WebViewer version directly

### ISSUE THREAD

**Issue by rdenman** [PDFTron/webviewer-ui#603]
For persistence purposes, I'd like to be able to grab the current WebViewer version from the WebViewer instance. I see that it already exists via `WebViewerInstance.CoreControls.DocumentViewer.prototype.version`, but it'd be nice if the version were "officially" available.

**Comment by Camo30** [comment]
For this you can use `WebViewerInstance.CoreControls.getBuild()` and `WebViewerInstance.CoreControls.getVersion()`, as described [here](https://www.pdftron.com/api/web/CoreControls.html#getVersion__anchor).

**Comment by ZhijieZhang** [comment]
Thanks for the help! @Camo30.

@rdenman Does the two APIs listed above work for your use case? Let me know how it works, and if it's all good I will close this issue. Thanks.

**Comment by rdenman** [comment]
Yes it does - must have missed in it in the docs! I'll close this out
