### ISSUE TITLE
PDFInfo version is incorrect: null 

### ISSUE THREAD

**Issue by tiimoS** [PDFTron/webviewer-ui#611]
After upgrading the webviewer from version 4.0.0 to 6.3.0, I get the warning in the console that the PDF info version is null. (CoreControls.js:188). I checked the code and the documentation but could not find any useful hints about the root cause of the issue. 
In addition, I am not entirely sure what the the pdf-info version actually is and how to set it manually to resolve the warning. 

Apart from that the update worked perfectly fine, and everything seems to work after fixing the breaking changes. 

WebViewer v6.3.0
Angular 8
Chrome 81.0.4044.138

**Comment by ZhijieZhang** [comment]
Do you mind posting a screenshot about what the warning looks like? I don't think I've seen that warning before so currently I'm not sure where in the code I should look into without further information.

Does this warning show up only for specific documents, or any kind of documents? Are you able to see the warning message at https://www.pdftron.com/samples/web/samples/viewing/viewing/?

If not I guess some of your code is triggering this warning in 6.3.0. One thing you can try is to comment out part of your code that's related to WebViewer, and see if the warning goes away. If not, comment out the other part, and see how it goes.

**Comment by tiimoS** [comment]
![Screenshot 2020-05-20 at 07 59 52](https://user-images.githubusercontent.com/26149808/82410333-f32bc200-9a6f-11ea-9351-e41433698e74.png)
Please find the screenshot attached. We only use the webviewer for pdfs. As far as I can see, the warning is shown with every pdf. I will try your proposal with commenting out as well. thx

**Comment by ZhijieZhang** [comment]
Thanks for sharing the screenshot.

It looks like the `version` attribute isn't set in the `pdf-info` tag. In most cases when we call `await instance.annotManager.exportAnnotations()`, the output XFDF data should contain a tag that looks something like the following:

```xml
<pdf-info xmlns="http://www.pdftron.com/pdfinfo" version="2" import-version="3">...</pdf-info>
```

Can you try using `exportAnnotations` and verify if there's no `version="2"` or `version="1"`?

Does this warning message show up for every document you are loading? At this point I can't tell why the `version` attribute isn't present, so I think we would need you to send over the PDF document to take a closer look at on our end.

If you don't want to share the document publicly, you can:
- Open a support ticket https://www.pdftron.com/form/request/ and attach the PDF document. The support ticket will be assigned internally in the team so one of my colleagues(or me) will help you further. At the same time, you can close the issue in the UI repo
- Send the document to my email at zzhang@pdftron.com

Thanks!

**Comment by ZhijieZhang** [comment]
I'm going to close this issue as it's not active, but feel free to reopen it and have a further discussion.
