### ISSUE TITLE
"annotationChanged" doesn't triggering after add/modify "Callout"

### ISSUE THREAD

**Issue by tarasromil** [PDFTron/webviewer-ui#620]
#### Hello

When I'm trying to edit "callout" or "free text" annotation in **canvas** area, _"annotationChanged"_ event doesn't triggering
So I can't track any changes in annotation.
Maybe there are an another way to catch this event?

**Also** found an issue with annotations status.
When you set some status for annotation,  _"annotationChanged"_ event fires twice (add/modify actions in row).
And when i'm trying to use `exportAnnotCommand` in _**modify**_ event, receiving empty `xfdf`, like:
```xml
<?xml version="1.0" encoding="UTF-8" ?>
<xfdf xmlns="http://ns.adobe.com/xfdf/" xml:space="preserve">
<fields />
<add />
<modify />
<delete />
</xfdf>
```
instead of xml with contents.

Can I somehow take corrent xml by passing annotation instance? 
**exportAnnotations** return batch of annotations, but I need single

Thanks.

WebViewer v6.3.1

**Comment by ZhijieZhang** [comment]
Thanks for bringing this to our attention.

To summarize, there're three issues:
1. The `annotationChanged` event isn't triggering when finishing editing a freetext or callout annotation.
2. Setting the status of an annotation will trigger two `annotationChanged` event, which is weird.
3. Calling `exportAnnotCommand` when `action` is `modified` outputs an empty XFDF data. 

For 1, I've made a PR in WebViewer to fix this issue. Once this PR went through you can get the build that contains the fix on the second day at https://www.pdftron.com/nightly/#stable/. If it's urgent for you to get this fix, I could also make a custom build and have you try it out.

2 and 3 are actually related, and we are having a discussion internally about what the solution will be. I agree that the behavior is weird, and ideally `modify` should not be triggered, but I think the current behavior shouldn't actually cause any bugs on your end after I looked closer at our code internally. I will keep you updated about these two issues.

**Comment by ZhijieZhang** [comment]
Hello,

The fixes for all the issues have been merged to the 6.3 branch. Please try the stable nightly build tomorrow and let me know how it goes.

To download the stable nightly build, go to https://www.pdftron.com/nightly/#stable/, click the latest date, and then click `WebViewer-6.3.1_2020-05-21_stable.zip`.

**Comment by tarasromil** [comment]
@ZhijieZhang Thank you for really fast response.

**Comment by tarasromil** [comment]
@ZhijieZhang Thank you for quick response.

I've tested new version and `modify` event works fine for canvas editing.

But settings status still produce 2 events (add/modify).
and when I'm trying to export by
```js
const xfdf = await this.annotationManager.exportAnnotCommand();
```
recieving this weird content (logs):
**action:**  _add_
**xfdf:**  
```xml
<?xml version="1.0" encoding="UTF-8" ?>
<xfdf xmlns="http://ns.adobe.com/xfdf/" xml:space="preserve">
<fields />
<add><text page="0" rect="158.85,291.11,178.85,311.11" color="#FFFF00" flags="hidden,print,nozoom,norotate" name="ede9d0cd-691e-37de-156d-038ae23be273" title="Taras Romilovych" subject="Sticky Note" date="D:20200522113118+03'00'" StrokeThickness="0" annotationNumber="2" creationdate="D:20200522113118+03'00'" inreplyto="7cedfc21-b026-a23c-c5fa-8c284b39a9b1" icon="Comment" state="Accepted" statemodel="Review"><contents>Accepted set by Taras Romilovych</contents></text></add>
<modify />
<delete />
</xfdf>
```

**action:**  _modify_
**xfdf:**  
```xml
<?xml version="1.0" encoding="UTF-8" ?>
<xfdf xmlns="http://ns.adobe.com/xfdf/" xml:space="preserve">
<fields />
<add />
<modify />
<delete />
</xfdf>
```

PS: `annotation.getContents()` returns correct content for me in both cases:
_"Accepted set by Taras Romilovych"_
Can it be related to async call of `exportAnnotCommand`?

Thanks!

**Comment by ZhijieZhang** [comment]
Ah I just realized that I made a typo in my last reply. The zip name should be `05-22` instead of `05-21`. However I just tried the `05-22` nightly build and found one small obfuscation issue. Therefore I generated a build manually that contains all the fixes you are looking for. You can download the build at https://pdftron.s3.amazonaws.com/custom/ID-zJWLuhTffd3c/WebViewer/WebViewer-6.3.1-status-annot-command.zip.

I've verified that all the issues are fixed in this build, but please take some time to verify on your end as well. This build is the latest nightly 6.3.1 plus a small obfuscation fix, so it's safe to use it in production.

Let me know how it goes and if you have any other questions. Sorry for the inconvenience!

**Comment by tarasromil** [comment]
Thank you @ZhijieZhang. I will try and close issue after testing

**Comment by tarasromil** [comment]
@ZhijieZhang Sorry, but it still produces `add` **&** `modify` events in a row
And I can't get correct `xml` while `await`ing from `exportAnnotCommand` in `modify` event

**Comment by ZhijieZhang** [comment]
I have trouble reproducing the issue using the custom build above. Here are the steps I used:

1. Click the link above and download
2. Unzip the package, open `viewing/viewing.js`, replace the file with the following code
```javascript
// @link WebViewerInstance: https://www.pdftron.com/api/web/WebViewerInstance.html
// @link WebViewerInstance.loadDocument: https://www.pdftron.com/api/web/WebViewerInstance.html#loadDocument__anchor

WebViewer(
  {
    path: '../../../lib',
    initialDoc: 'https://pdftron.s3.amazonaws.com/downloads/pl/demo-annotated.pdf',
  },
  document.getElementById('viewer')
).then(instance => {
  instance.annotManager.on('annotationChanged', async (annotations, action) => {
    console.log(annotations[0], action);
    console.log(await instance.annotManager.exportAnnotCommand());
  })

  samplesSetup(instance);
  document.getElementById('select').onchange = e => {
    instance.loadDocument(e.target.value);
  };

  document.getElementById('file-picker').onchange = e => {
    const file = e.target.files[0];
    if (file) {
      instance.loadDocument(file);
    }
  };

  document.getElementById('url-form').onsubmit = e => {
    e.preventDefault();
    instance.loadDocument(document.getElementById('url').value);
  };
});
```javascript
- Run `npm install` and then `npm start`
- Go to `http://localhost:3000/samples/viewing/viewing/` and open developer console
- Open notes panel, click the first note, set the status to `Accepted`.
- Only see one `annotationChanged` event trigger with `add` and `xml` is correct.

If you follow the above steps are you able to reproduce the issue? Thanks.

**Comment by tarasromil** [comment]
@ZhijieZhang I've just pulled latest changes from 6.3 branch, so it work for me fine.
Thanks you so much.
Closing
