### ISSUE TITLE
Get annotations sorted by occurrence in document

### ISSUE THREAD

**Issue by tiimoS** [PDFTron/webviewer-ui#623]
Currently, when I run `annotManager.getAnnotationsList());` I get the list of annotations, sorted by their creation date. Is there a way to get the list of annotations sorted by their location in the document, so annotations that appear at the beginning of the page are listed before the ones at the end of the page? I see that there we have the pageNumber, X and Y coordinates and the width and height of the Annotation that could be used for such purposes, but that doesn't work well with multi-column documents.

**Comment by ZhijieZhang** [comment]
Unfortunately we don't an API that returns a list of annotations sorted by their location. But based on what you mentioned it seems to me that you are looking for the same functionality as the `Position` button in the left notes panel.

The following code shows the calculations the `Position` button uses, hopefully it will help:
https://github.com/PDFTron/webviewer-ui/blob/ae70007f70d0f4879b008fd489af4966ab131ace/src/constants/sortStrategies.js#L8-L30
https://github.com/PDFTron/webviewer-ui/blob/ae70007f70d0f4879b008fd489af4966ab131ace/src/helpers/orientationManager.js#L1-L34

I don't think I have a multi-column document on my end, and I'm not sure what part doesn't work well. I would suggest playing around with Annotation APIs to see if you can get the desired results. If you need us to take a look as well, please send over the document, and describe what doesn't work well and what the expected result is. Thanks.

**Comment by ZhijieZhang** [comment]
I'm going to close this issue as it's not active. Feel free to reopen and discuss more.
