### ISSUE TITLE
Hide Ribbons on Desktop

### ISSUE THREAD

**Issue by tiimoS** [PDFTron/webviewer-ui#853]
Is there a way to hide the new ribbons UI on desktop? On Desktop we would like to have a single header without the ribbons, i.e. with the annotation tool buttons showing directly in the header and not in the additional toolsHeader or rather toolbarGroup-Annotate. 

So, on mobile it should look like this: 
![image](https://user-images.githubusercontent.com/26149808/90750856-b329e480-e2d5-11ea-81fc-fbf84fdbb34e.png)

and on Desktop just a single header with the annotation tools directly in it (without any ribbons or additional toolsHeader) 
![Screenshot 2020-08-20 at 11 10 51](https://user-images.githubusercontent.com/26149808/90751190-1ae02f80-e2d6-11ea-84ce-e44f604e3124.png)
When looking at the default header items (getItems()), the ribbon is a custom-element with the className "custom-ribbons-container" in the list of tool buttons. I have tried adding hidden: ['desktop'] to this custom element, but it does not yield in the desired result. The ribbon dropdown is still visible in the desktop header
![image](https://user-images.githubusercontent.com/26149808/90750462-1e26eb80-e2d5-11ea-8653-e5c277ed7ca2.png)

The 'hide-in-desktop' is added successfully to the div 'custom-ribbons-container' but the dropdown it contains is still shown. 

![image](https://user-images.githubusercontent.com/26149808/90750439-1404ed00-e2d5-11ea-8a15-f65d4e338c48.png)

So far I have not found any way to get this to work. Any help would be highly appreciated.

**Comment by ZhijieZhang** [comment]
@khein-pdftron Can you take a look at this one? Thanks

**Comment by khein-pdftron** [comment]
Hello. There seems to be an issue of css specificity when using hide-in-desktop with Ribbons. Even if it did work though, Ribbons are special case though and setting `display: none` would collapse the right side buttons. Instead you can do as specified below:

To hide the Ribbons at just desktop screen-width, you can modify https://github.com/PDFTron/webviewer-ui/blob/2c7cfd4461285f9e1d7ef4931a72fd8c7294d62c/src/components/Ribbons/Ribbons.scss#L9

Add the following to the `.custom-ribbons-container` class

`  
@include desktop {
    visibility: hidden;
 }
`
