### ISSUE TITLE
Expose Annotation Parent property

### ISSUE THREAD

**Issue by viezel** [PDFTron/webviewer-ui#872]
If I want to use find a parent of the current annotation, I don't have a specific property to use. I need to reach for a `annotation.AE` instead of the missing `annotation.Parent`. 

We already have `annotation.Subject` and `annotation.Id` etc exposed - so lets get parent. 

example code, here I want to find the parent and select the parent annotation. 

```javascript
function selectAnnotation(annotManager, annotationId) {
    annotManager.deselectAllAnnotations();
    var annotation = annotManager.getAnnotationById(annotationId);
    if (null !== annotation) {
        // get parent annotation
        if(annotation.AE !== null) {
            annotation = annotManager.getAnnotationById(annotation.AE);
        }

        annotManager.selectAnnotation(annotation);
        annotManager.showAnnotation(annotation);
        annotManager.jumpToAnnotation(annotation);
    }
}
```

**Comment by mparizeau-pdftron** [comment]
I think the exposed property that you're looking for `annotation.InReplyTo`

You can see it listed here, though it looks like the description should be updated as it isn't just for sticky note annotations https://www.pdftron.com/api/web/Annotations.MarkupAnnotation.html#MarkupAnnotation__anchor
We'll update the description

**Comment by ZhijieZhang** [comment]
Just want to give you an update that the documentation has been updated. I'm closing this issue for now as it becomes inactive and I think the issue is resolved. Feel free to reopen it to discuss further.
