### ISSUE TITLE
Framer Motion animations choppy

### ISSUE THREAD

**Issue by henry-chris** [PDFTron/webviewer-ui#876]
Since upgrading to 7.0.  The Left and Right Panel animations have been very choppy in certain situations. 

Less powerful systems, high CPU usage at the time, etc...  Just doesn't look great in many cases.

In addition, in debug the animations are extremely slow and choppy all the time.  We keep thinking that we've messed something up, but it just seems to be standard.

**Comment by khein-pdftron** [comment]
Hello,

Thank you for reporting this. We are also not satisfied with the performance of framer-motion. I will be changing back the animations to css  animations. You can expect it in version 7.2 of WebViewer.

**Comment by ZhijieZhang** [comment]
Just want to follow up that this issue should be fixed in 7.2. Can you give it a try? I'm closing this issue for now. Feel free to reopen it to discuss further.
