### ISSUE TITLE
Make Notes Icon for Attachment a paperclip

### ISSUE THREAD

**Issue by henry-chris** [PDFTron/webviewer-ui#878]
Match icons on the PDF and the right panel / notes panel.  

Right now, it's just a filled in circle.

![image](https://user-images.githubusercontent.com/4165721/93650948-7f75d380-f9d5-11ea-9e50-a4391933e496.png)

**Comment by ZhijieZhang** [comment]
Sorry for the delay in the reply! 

We will make a fix for this shortly, and update the issue once the fix is merged in.
