### ISSUE TITLE
Opening the search panel does not focus the input

### ISSUE THREAD

**Issue by tekilla123** [PDFTron/webviewer-ui#887]
Issue:
user has to select the search input to start searching

Reproduce (tested with Chrome):
- when document is loaded user presses ctrl+f or opens the search panel
- wants to instantly start typing the search term
- the search input field should be focus, but is not 

Note
.focus is registered as an effect in SearchOverlay.js:35 but does not seem to work.

**Comment by ZhijieZhang** [comment]
Hey thanks for bringing this up. We will take a further look and let you know when we have more information.

**Comment by ZhijieZhang** [comment]
Just want to give you an update that the reason for this seems to be that the search input in the panel is only focused when the panel is mounted. We should be able to open a PR internally to fix this issue today.

In the future, please submit the issue via https://www.pdftron.com/support/. This helps us analyze the ticket, and usually result in a faster respond time.

Thanks and have a nice day!

**Comment by ZhijieZhang** [comment]
I believe this issue has been fixed in 7.3.1. Can you try it out and let us know how it goes? Closing this issue for now.
