### ISSUE TITLE
Err: Custom does not exist in type WebViewerOptions

### ISSUE THREAD

**Issue by priteshbonde** [PDFTron/webviewer-ui#889]
I am trying to set custom data to the Webviewer contructor as in this [document](https://www.pdftron.com/documentation/web/guides/config-files/#passing-custom-data) .
Below is my code for initialisation.

 ```
           WebViewer(
                {
                    config: "assets/lib/webviewer/webviewer.config.js",
                    custom: JSON.stringify(this.customConfig),
                    disabledElements: [
                        "progressModal",
                        "errorModal",
                        "fileAttachmentToolGroupButton",
                        "applyWatermark",
                        "rubberStampToolGroupButton",
                        ] ,

                    enableAnnotations: true,
                    enableAzureWorkaround: true,
                    extension: "xod",
                    path: "assets/lib/webviewer/",
                } as any,
                this.element.nativeElement,
            ).then((instance) => {
                this.viewerInstance = instance;
                instance.enableElements(["bookmarksPanel", "bookmarksPanelButton"]);
                this.viewerInstance.docViewer.on("documentLoaded", this.wvDocumentLoadedHandler.bind(this));
                this.wvReadyHandler();
            });
        },
            () => this.fail.bind( this ) );
```

I am getting an error `Object literal may only specify known properties, and 'custom' does not exist in type 'WebViewerOptions'`
Am i missing something?

**Comment by ZhijieZhang** [comment]
It looks like we didn't use JSDoc for documenting the `custom` property so it doesn't show in our TS declaration file, which leads to this issue.

This issue isn't WebViewer UI related, could you please open a ticket via https://www.pdftron.com/form/request/? From there one of the web team will get back to you. Thanks!

**Comment by ZhijieZhang** [comment]
I just want to let you know that we have an internal PR that will fix this issue. The fix is expected to be available in the next WebViewer release, which we expect to be out around the end of January.

**Comment by ZhijieZhang** [comment]
I'm closing this issue because the fix has been merged. Could you try the latest 7.2 build and see if it resolves on your end? If not, feel free to reopen this issue. Thanks!
