### ISSUE TITLE
Highlighting appears very choppy in 7.2.0

### ISSUE THREAD

**Issue by georgiemathews** [PDFTron/webviewer-ui#890]
You can observe this by trying to select multiple lines of document text in the [demo](https://www.pdftron.com/webviewer/demo/).
The selected area flickers as you keep highlighting.
This was observed for the first time in 7.2.0.

We were unable to reproduce this issue in 7.1.2.
We rely on a fix in 7.2.0 so we're hoping we don't have to downgrade to resolve this issue.

**Comment by ZhijieZhang** [comment]
Thanks for reaching out!

I'm able to reproduce the selection issue and it's actually an issue in the WebViewer Core(CoreControls.js).
Could you please open a support ticket via https://www.pdftron.com/form/request/?

Thanks, and let me know if you have any concerns or other questions.
