### ISSUE TITLE
Releases not tagged

### ISSUE THREAD

**Issue by peterpeterparker** [PDFTron/webviewer-ui#891]
Hi,

In July 2020, I suggested to improve the traceability of the repo and versions by tagging these releases.

Suggestion which was [accepted](https://github.com/PDFTron/webviewer-ui/issues/541#issuecomment-6026995419) by the team and applied to [v7.0.0](https://github.com/PDFTron/webviewer-ui/releases/tag/v7.0.0).

Since then, there were four versions (7.1.x and 7.2.x) but, none have been tagged.

Did the team went backwards and releases aren't going to be tagged properly anymore? Or can you tag these?

**Comment by ZhijieZhang** [comment]
Thanks for bringing this up. No we didn't go backwards. I just tagged `v7.1.0`, `v7.1.1`, `v7.1.2` and `v7.2.0`.
The changelog for the UI has been moved to https://www.pdftron.com/documentation/web/changelog/v7-2-0/.

I think this issue has been addressed so I'm going to close it. If not, feel free to reopen it. Thanks.

**Comment by peterpeterparker** [comment]
Thx @ZhijieZhang
