### ISSUE TITLE
Annotation popup not shown when the left panel is visible

### ISSUE THREAD

**Issue by jdlib** [PDFTron/webviewer-ui#896]
WebViewer 7.2.0
Firefox 84.0.2 on Win10, Safari on iOS 14.3

If I click on an existing annotation then the annotation is selected and an annotation popup is shown below or nearby the annotation (i.e. a `<div class="Popup AnnotationPopup open react-draggable">`), offering me annotation related tools to edit the annotation.
But if the left panel (containing thumbnails and outline) is open then the annotation popup is not shown when the annotation is selected.
Is this is a bug or by design? If the later can I change the behavior?
Thank you.

**Comment by bollain** [comment]
Thanks for reaching out - this is a bug that was addressed by this commit to the 7.2 branch:
https://github.com/PDFTron/webviewer-ui/commit/448efda21757873db318b8f861ad75ad310020f3

You can build the UI by pulling this branch, or you can get the package from our nightly builds here:
https://www.pdftron.com/nightly/#stable/

This will also be part of our 7.3 WebViewer release, which is expected mid February.

Regards
