### ISSUE TITLE
Problems with stamp annotations based on camera photo

### ISSUE THREAD

**Issue by jdlib** [PDFTron/webviewer-ui#897]
WebViewer 7.2.0
Safari on iOS 14.3 (iPad Air 2)

1)
If I insert a stamp annotation on iOS I can choose an existing photo or take a photo with the camera.
In our system annotations are stored on the server and presented to the user again when the PDF is reopened in WebViewer.
Stamp annotations using existing photos work fine. 
Stamp annotations using photos taken with the camera seem to work (photo is shown on the page) but when the PDF is reopened the annotation is lost, since it was never sent to server.
Is there an issue with photos taken from the camera?

2) 
related to this problem: the feature to insert a stamp using the camera does not seem to be available on Android devices? Is this true, or is there a way to enable this feature on Android?

Thanks

**Comment by ZhijieZhang** [comment]
Hi there, sorry for the delay in the reply! I believe we've just replied you via the support ticket.
To keep the conversation just in one place, I'm closing this issue.
