### ISSUE TITLE
Running a local file

### ISSUE THREAD

**Issue by capt-pyro** [PDFTron/webviewer-ui#898]
I tried to run this project and it pointed to a default url. I changed the url to a local file (file:///home/user/Downloads/test.pdf) and wasn't able to run it. It said pdftron wasnt able to run file URLS. Is there a way to do this>

**Comment by ZhijieZhang** [comment]
Unfortunately due to browser constraints WebViewer isn't able to read the document that's on your local disk. You could try hosting the document and point the url to it.
