### ISSUE TITLE
pdftron Webviewer - range request are not rendering in IE 10 and IE 11 browsers.

### ISSUE THREAD

**Issue by DevalGtl** [PDFTron/webviewer-ui#899]
Hello,

I am using Core version: "7.2.0" and UI version: "7.2.0".  

I got an error while loading the document in IE.
 
Error: Error retrieving file: /liweb/documents/getpartialfilecontent?docId=4191022. Received return status 400.
 
So I realize that the range request is working in the IE browser.
This error is happening on the page load, This stopped working in IE browser but ok in another browser, it is not sent partial range request. so I get that the error.

![400_IE](https://user-images.githubusercontent.com/76045143/105803640-ea5a9b00-5fc3-11eb-92b4-7855ac4c93c2.PNG)

**Comment by ZhijieZhang** [comment]
Hello! This looks like to be a WebViewer issue instead of UI. Could you please open a ticket via https://www.pdftron.com/form/request/? In the ticket, please forward the document you are trying with, and how you are setting up WebViewer.
