### ISSUE TITLE
Issue templates

### ISSUE THREAD

**Issue by peterpeterparker** [PDFTron/webviewer-ui#902]
### Documentation Feedback

It would be nice to add some issue templates to this repo so that issues can be reported by following predefined patterns.

**Comment by ZhijieZhang** [comment]
Sorry for the delay in the response! I think I have some time working on this today. Plan is to refer to what we have at https://www.pdftron.com/form/request/

**Comment by ZhijieZhang** [comment]
Just added two templates, so closing this issue.
