### ISSUE TITLE
Fix Imperfect Japanese Translations

### ISSUE THREAD

**Issue by Ryosuke-ob** [PDFTron/webviewer-ui#905]
Version:7.2

We deal with the product which include PDFTron features for Japanese market.  
As of now, Japanese translations are not perfect.
So, I fixed the translations to improve the usability for us.

I will only change the following json file. I hope pull request will be accepted.
https://github.com/PDFTron/webviewer-ui/blob/7.2/i18n/translation-ja.json

**Comment by ZhijieZhang** [comment]
Thanks for the contribution! Closing this issue now because the PR has been merged.
