### ISSUE TITLE
[Feature Request] Page selection event in leftPanel

### ISSUE THREAD

**Issue by piu130** [PDFTron/webviewer-ui#909]
**Is your feature request related to a problem? Please describe.**
We want to enable/disable some UI elements, when de user selects pages in the left panel.
There is no event to hook into page selection.

**Describe the solution you'd like**
Provide an event `instance.on('pageSelectionChanged', (selectedPages: number[]) => /* do some stuf */)` so we can listen to page selection changes.
 
**Why is this feature important to your users?**
We have some custom copy/paste buttons, to copy pages from one viewer-window to another.
The copy button should be disabled when there is no page selected.

**Desired timeline**
As soon as possible.

**Comment by ZhijieZhang** [comment]
Sorry for the delay in the reply! 

I would like to double check with you to see if you are referring to the thumbnails panel in the left panel? And you would like to listen to the new event to see what thumbnails have been selected or deselected, and enable or disable certain buttons?

**Comment by piu130** [comment]
Exactly. By selecting pages I mean the thumbnails in the left panel. We need an event when this selection changes, preferably with the selection as payload.

**Comment by ZhijieZhang** [comment]
Thanks for the clarification!

We've added the feature to our backlog to be worked on in the future. We don't have a timeline for when it will be available but if it does get worked on we'll let you know when it's available in an experimental build to test out and the estimated official release date.

If this is a critical improvement for you, and you need a fixed timeline for this to be completed by, then the next step would be to do a paid custom engineering project. If you are interested in that, please fill in this form.
https://www.pdftron.com/form/professional-services/

**Comment by jasonhu777** [comment]
Hello, 

Thank you for your patience. 
There is a new event called 'selectedThumnailChanged', which would be fired if there is any change in the selection of thumbnails, and the payload is all currently selected thumbnail page indexes. 

You can test it at: https://jasonhu-pdftron.web.app/thumbnailSelected/, I already set up the event and the outputs can be viewed in the console.

I also noticed that there is another feature request: https://github.com/PDFTron/webviewer-ui/issues/904 created by you, which is quite similar to this one, so I was wondering if this new 'selectedThumbnailChanged' event would be enough. If it is not, please let me know so we can discuss the next steps which might include a whole new event.

**Comment by piu130** [comment]
This looks great. Thank you!
Will this be available in version 7? Or do you have a release date for version 8?

@jasonhu777 The other issue is about drag and drop. It's not related to this issue.

**Comment by jasonhu777** [comment]
No problem! 
It will be available in webviewer 8.0, which was branched today, hopefully we would be able to release it in two weeks. 
It is already available in experimental nightly build.
