### ISSUE TITLE
[Bug] Selecting a page two times

### ISSUE THREAD

**Issue by piu130** [PDFTron/webviewer-ui#910]
**WebViewer version**
7.3.0

**The current behavior**
One can select a page two times.

**The expected behavior**
The page should only be selected once.

**Steps to reproduce**
- Open demo https://www.pdftron.com/webviewer/demo/
- Open leftPanel
- Select a page, deselect it and select it again
- The `input` contains now `1, 1`, `getInstance().getSelectedThumbnailPageNumbers()` returns `[1, 1]`

**Comment by piu130** [comment]
I reproduced it now on [your site](https://www.pdftron.com/samples/web/samples/viewing/viewing/) with Chrome and Edge Chromium. Maybe you didn't press the ctrl-key for selecting page 1 the second time?
Here an example for selecting p1, deselecting p1, selecting p1, selecting p2. Ends in `1, 1-2` as you can see in the bottom left.
![p1](https://user-images.githubusercontent.com/12607663/111861670-70ee8180-8950-11eb-92df-eae3d9457f7d.png)
![p2](https://user-images.githubusercontent.com/12607663/111861677-75b33580-8950-11eb-8e67-268b40a5bde7.png)
![p3](https://user-images.githubusercontent.com/12607663/111861679-78ae2600-8950-11eb-9ebb-cae2a1c8624d.png)
![p4](https://user-images.githubusercontent.com/12607663/111861684-7a77e980-8950-11eb-9538-ca6b3ae4cb2c.png)

**Comment by ZhijieZhang** [comment]
Ah you are right. I wasn't holding the Command key when I selected the thumbnail for the second time. Now I can reproduce the issue.

**Comment by bollain** [comment]
This issue has now been fixed, and is available in our latest builds for 8.3.
