### ISSUE TITLE
[Bug] Push version in 'legacy/7.3' branch to latest version

### ISSUE THREAD

**Issue by Camo30** [PDFTron/webviewer-ui#922]
**WebViewer version**
v7.3

**The current behavior**
The version string of the file `package.json` in the branch [legacy/7.3](https://github.com/PDFTron/webviewer-ui/tree/legacy/7.3) seems outdated as it points to version 7.3.2 but it seems it's already version 7.3.3 which is the latest available for version 7. Please push an update to this file. Thanks!

**Comment by bollain** [comment]
Hi @Camo30,

Thanks for letting us know about this oversight, I have made the change and it should be reflected in this repo in about a day or so.
