### ISSUE TITLE
[Bug] toolsHeader element isn't properly hidden on mobile

### ISSUE THREAD

**Issue by jgoux** [PDFTron/webviewer-ui#923]
**WebViewer version**
8.0.1

**The current behavior**
When using the `disabledElements` on WebViewer : 
```tsx
void WebViewer(
      {
        // list of all elements : https://www.pdftron.com/documentation/web/guides/hiding-elements/#list-of-elements
        disabledElements: [
          // Header :
          "header",
          "toolsHeader",
          // Popups :
          "contextMenuPopup",
          // - annotationPopup :
          "annotationCommentButton",
          "annotationStyleEditButton",
          "linkButton",
        ],
        path: "/webviewer/lib",
      },
      // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
      viewerRef.current!
    )
```

The `toolsHeader` element is still showing up on mobile.

**The expected behavior**

The `toolsHeader` element should be hidden on mobile as well.

It seems that the responsive height for the `toolsHeader` is conflicting with the one when the `.closed` className is applied to it : 
![image](https://user-images.githubusercontent.com/1443499/132019325-c1623b6a-3509-4776-b4f7-33860f6e3357.png)

I think this should fix it : 
```css
@media (max-width: 900px) {
  .App:not(.is-in-desktop-only-mode) .HeaderToolsContainer:not(.closed) {
      height: 52px;
  }
}
```

**Steps to reproduce**

**Comment by bollain** [comment]
Hi @jgoux,

Thanks for the report! We had fixed this issue in our dev/master branch, but it had not been merged into 8.0. This has now been addressed:
https://github.com/PDFTron/webviewer-ui/commit/db98fc628c906a7172e3dd536d8d7eeeb47afa9f
