### ISSUE TITLE
[Bug] Build Error (PageManipulationOverlay.scss not found in the source)

### ISSUE THREAD

**Issue by chathuraasanka** [PDFTron/webviewer-ui#926]
I Used V 8.1, and try to build the library but there was an while building. 

ERROR in ./src/components/PageManipulationOverlay/PageManipulationOverlay.js
Module not found: Error: Can't resolve './PageManipulationOverlay.scss' in 'D:\Sample Apps\PDFTron\src\components\PageManipulationOverlay'
@ ./src/components/PageManipulationOverlay/PageManipulationOverlay.js 6:0-40
@ ./src/components/PageManipulationOverlay/PageManipulationOverlayContainer.js
@ ./src/components/PageManipulationOverlay/index.js
@ ./src/components/App/App.js
@ ./src/components/App/index.js
@ ./src/index.js

I looked the file but couldn't find the "PageManipulationOverlay.scss" could anyone please share the file if anyone has it or give me solution to solve this issue

**Comment by bollain** [comment]
Hi @chathuraasanka,

Thanks for reporting this. I have made a fix on my end, which will be reflected on this repo in the next day or two. In the meantime, you can delete this line from `PageManipulationOverlay.js`:
```
import './PageManipulationOverlay.scss';
```

This file is actually empty so there are no issues with removing it. I'll close this issue but feel free to reopen it if you have further issues.

**Comment by chathuraasanka** [comment]
Noted and Thanks @bollain
