### ISSUE TITLE
[Bug] Toolbar off center

### ISSUE THREAD

**Issue by naueramant** [PDFTron/webviewer-ui#937]
**WebViewer version**
7.3.1 and 8.1.0

**The current behavior**
The toolbar tabs are off center in relation to the viewer and instead centered in relation to the content of the toolbar.

**The expected behavior**
To be centered in relation to the viewer instead of the content in the toolbar.

**Steps to reproduce**
Open the newest sample or demo for Webviewer 8.1.0

**Other notes**

The difference can be seen here:

7.3.1
![2](https://user-images.githubusercontent.com/6765915/143254936-a7b06d9f-c686-4d0f-85b8-4b437aa55cc2.png)

8.1.0
![1](https://user-images.githubusercontent.com/6765915/143254956-f734cef2-7159-471f-8951-6930f8d4abb2.png)

There are theming differences between the two pictures but please ignore that, they do not affect the centering.

**Comment by bollain** [comment]
Hi @naueramant,

Thanks for the report. This issue is already on our bug list. I can't provide an estimate on when it will be fixed, but an update will be provided on this issue when we address this.

**Comment by bollain** [comment]
Hi @naueramant,

This bug has been fixed and is part our 8.3 release:
https://www.pdftron.com/documentation/web/changelog/v8-3-0/#new

Thanks again for the report.
