### ISSUE TITLE
[Bug] Ribbon is not centered in the viewport

### ISSUE THREAD

**Issue by ZhijieZhang** [PDFTron/webviewer-ui#942]
**WebViewer version**
8.2.0

**The current behavior**
The ribbon component is centered with respect to its container(`ribbons-container centered-on-empty-space`), not with respect to the entire viewport. Since the toolbar below the ribbon is centered in the viewport, this makes the position of ribbon a bit off.

**The expected behavior**
I remember in the previous versions the ribbon component is centered in the entire viewport, so I thought that was the expected behavior. If this is a design change then please ignore this report.
<img width="1894" alt="Screen Shot 2021-12-21 at 8 07 15 AM" src="https://user-images.githubusercontent.com/25110092/146961828-f715c67d-fee0-4598-b7fb-62d5327fbc1a.png">

**Steps to reproduce**
1. Open https://www.pdftron.com/samples/web/samples/viewing/viewing/

**Comment by bollain** [comment]
Hi @ZhijieZhang!!

Thanks for your report. This appears to be related to this [issue](https://github.com/PDFTron/webviewer-ui/issues/937).

It is on our list to fix, as it seems this is a result of recently adding more options to the Ribbons. It's on the list and we'll try to get this one addressed soon.  

Thanks again!

**Comment by ZhijieZhang** [comment]
Np. Thanks! Since it sounds like a duplicate feel free to close this issue.

**Comment by bollain** [comment]
Hi @ZhijieZhang!

This bug has been fixed and is part of our 8.3 release:
https://www.pdftron.com/documentation/web/changelog/v8-3-0/#new

Thanks again for the report and take care!
