### ISSUE TITLE
[Bug] Webviewer ZIP file cannot be extracted via npm

### ISSUE THREAD

**Issue by scottyeung** [PDFTron/webviewer-ui#944]
**WebViewer version**
8.2
**The current behavior**
Webviewer ZIP file cannot be extracted via npm run download-webviewer
**The expected behavior**
Webviewer can be extracted with Unzip utilities
**Steps to reproduce**
1. npm install
2. npm run download-webviewer

<img width="700" alt="Screen Shot 2022-01-05 at 10 55 50 AM" src="https://user-images.githubusercontent.com/23536187/148153724-ade20836-f3d3-4f32-af1a-328910260fbb.png">

**Comment by bollain** [comment]
Hey @scottyeung,

Are you able to install the WebViewer dependencies using the NPM package?
https://www.npmjs.com/package/@pdftron/webviewer
https://www.pdftron.com/documentation/web/get-started/npm/#1-install-via-npm

We've had this issue before with the Yazul package, and no longer recommend using the `download-webviewer` script.

**Comment by bollain** [comment]
Closing issue as no update has been provided - feel free to re-open if there is anything else you would like us to look at.
