### ISSUE TITLE
[Bug] Redaction don't respect PageNumber

### ISSUE THREAD

**Issue by creage** [PDFTron/webviewer-ui#946]
**WebViewer version** 8.2.0

**The current behavior**
Searching for text, and then applying he redaction, applies them to ALL of pages.

**The expected behavior**
Redactions should be applied to the places where they belong

**Steps to reproduce**
* Open the https://www.pdftron.com/webviewer/demo/redaction
* Upload the attached document
* Search for string "SOM"
* Apply redactions

[TestDocumentPDF.pdf](https://github.com/PDFTron/webviewer-ui/files/7862201/TestDocumentPDF.pdf)

**Comment by bollain** [comment]
@creage Thanks for this report. The bug itself is in the showcase demo of WebViewer, not WebViewer itself as that redaction workflow is built on top of the viewer. We will be looking at this and when it is fixed I will provide an update.

**Comment by creage** [comment]
@bollain well, actually we have the same behavior in the redaction flow we built based on the webviewer. I mentioned demo page for easier repro steps only.

**Comment by bollain** [comment]
@creage Thanks for submitting the ticket through our support channels. It appears this may be related to how this particular document was created. We are looking into it and will provide further updates in the ticket. I will close this issue now.
