### ISSUE TITLE
[Feature Request] Please include sourcemaps into the NPM package

### ISSUE THREAD

**Issue by creage** [PDFTron/webviewer-ui#948]
**Is your feature request related to a problem? Please describe.**
Developing custom extensions to Webviewer requires a lot of debugging, and debugging Webviewer code that is minified (in a very bad way) is very difficult.

**Describe the solution you'd like**
Since you are using Webpack for bundling your assets, would be nice to have **sourcemaps**, both for JS and styles, generated and shipped with NPM package. It shouldn't be difficult, but will help developers a lot!

**Desired timeline**
ASAP

**Comment by bollain** [comment]
@creage What type of custom extensions are you writing, and have you forked the UI or are you just using the NPM package? 

WebViewer is split into the UI and Core, the UI is open source and you are able to build it locally if you want to step through unminified code. However, the core is part of our closed source repo and we cannot provide any unminified versions of it or a way to unminify it. The core code would be anything involving abstractions such as the AnnotationManager, DocumentViewer, or any of the code for the tools.

If you are having issues writing custom code for WebViewer we are always happy to look over your code, simply send in a ticket through our Freshdesk channel and a developer will be assigned to it.

**Comment by creage** [comment]
@bollain what we do is some additional UI buttons, enabling some of the PDFTron features, like redactions, watermarks, etc.

So, what we are interested in is a set of sourcemaps for the UI part mainly. Building it locally is not easy now, as we install the viewer as NPM package, and your package does not contain original sources of the UI part.

If you don't want to add sourcemaps to the NPM package, then please consider publishing original sources of the UI instead, so we can build from them, adding sourcemaps during our build process.

Thank you.

**Comment by bollain** [comment]
@creage after discussing this internally, we will be adding the sourcemap for the UI repo. It is currently under review, and will hopefully be merged in the next few days. Once merged you'll be able to get an updated build from the stable nightly builds.

**Comment by bollain** [comment]
Hi @creage,

The source maps have now been merged into the repo. We will release them along with 8.3, which should be ready in the next couple of weeks. If you want to test it out now you can try downloading our nightly experimental branch (in about 24 hours from now).
https://www.pdftron.com/nightly/#experimental/

**Comment by bollain** [comment]
Hi @creage,

Good news: we have released 8.3 and it now includes the source maps for the UI. You can get it from our downloads page:
https://www.pdftron.com/documentation/web/changelog/v8-3-0/#new

I will close this issue now.
