### ISSUE TITLE
Fix Japanese Translations

### ISSUE THREAD

**Issue by Ryosuke-ob** [PDFTron/webviewer-ui#949]
Version: 8.2

Following #905, #906, #907, I would like to you to merge my pull request about Japanese translations.

I have changed the following json file and addressed the strings added since the last time.
https://github.com/PDFTron/webviewer-ui/blob/8.2/i18n/translation-ja.json

**Comment by bollain** [comment]
Thanks for submitting this for review! The PR has been merged.
