### ISSUE TITLE
[Bug] unable to install download-WebViewer

### ISSUE THREAD

**Issue by zkrige** [PDFTron/webviewer-ui#961]
**WebViewer version**
8.3.0

**The current behavior**
throws exception

**The expected behavior**
downloads and extracts

**Steps to reproduce**

npm run download-webviewer
```
Downloading WebViewer... 100%
Download completed.

Extracting WebViewer...node:events:371
      throw er; // Unhandled 'error' event
      ^

Error: invalid central directory file header signature: 0x8001403
    at /Users/zayinkrige/.npm/_npx/58d3a7a62a793155/node_modules/yauzl/index.js:258:70
    at /Users/zayinkrige/.npm/_npx/58d3a7a62a793155/node_modules/yauzl/index.js:631:5
    at /Users/zayinkrige/.npm/_npx/58d3a7a62a793155/node_modules/fd-slicer/index.js:32:7
    at FSReqCallback.wrapper [as oncomplete] (node:fs:660:5)
Emitted 'error' event on ZipFile instance at:
    at emitError (/Users/zayinkrige/.npm/_npx/58d3a7a62a793155/node_modules/yauzl/index.js:232:8)
    at emitErrorAndAutoClose (/Users/zayinkrige/.npm/_npx/58d3a7a62a793155/node_modules/yauzl/index.js:227:3)
    at /Users/zayinkrige/.npm/_npx/58d3a7a62a793155/node_modules/yauzl/index.js:258:42
    at /Users/zayinkrige/.npm/_npx/58d3a7a62a793155/node_modules/yauzl/index.js:631:5
    at /Users/zayinkrige/.npm/_npx/58d3a7a62a793155/node_modules/fd-slicer/index.js:32:7
    at FSReqCallback.wrapper [as oncomplete] (node:fs:660:5)
```

**Comment by bollain** [comment]
Hello @zkrige,

Are you able to install the WebViewer dependencies using the NPM package?
https://www.npmjs.com/package/@pdftron/webviewer
https://www.pdftron.com/documentation/web/get-started/npm/#1-install-via-npm

We've had this issue before with the Yazul package, and no longer recommend using the download-webviewer script.

**Comment by zkrige** [comment]
Yes I'm able to manually install the stuff into the lib folder. Perhaps this GitHub readme should be updated to reflect correct installation steps - it might help towards getting WebViewer up and running in a local environment :)

**Comment by bollain** [comment]
Thanks for the feedback @zkrige. We've updated the docs to reflect the preferred installation steps.

I will close this issue now but dont hesitate to reach out if you have any other questions, which you can also submit directly via a support ticket:
https://www.pdftron.com/form/trial-support/
