### ISSUE TITLE
[Bug] "Add New Signature" button is shy

### ISSUE THREAD

**Issue by qguv** [PDFTron/webviewer-ui#971]
**WebViewer version**

8.3.3. I couldn't reproduce this behavior in 8.2.0.

**The current behavior**

There are cases when the "Add New Signature" button (located in the "Insert" and "Fill and Sign" menus) doesn't immediately appear and cases where it disappears. Here are some interesting cases:

+ When moving from the "Annotate", "Shapes", or "Redact" bar to the "Insert" or "Fill and Sign" bar, a gray box labelled "No Presets" will show in place of the "Add New Signature" button. The latter appears if the user clicks "Insert" or "Fill and Sign" (again). Note that clicking "Annotate" → "Insert" → "Insert" will cause the "Add New Signature" button to be shown, but so will "Annotate" → "Insert" → "Fill and Sign", or "Annotate" → "Fill and Sign" → "Insert".
  + The "Signature" button in the menu bar below is deselected when "No Presets" is showing and selected when "Add New Signature" is showing.
+ If the "Add New Signature" button is shown in the "Insert" or "Fill and Sign" menus and the mouse hovers over text in the document, the button will be replaced with a gray box labelled "No Presets".
  + The "Signature" button in the menu bar below is also deselected in this case.

**The expected behavior**

The "Add New Signature" button should appear when the "Insert" or "Fill and Sign" menus are open, and should not disappear when hovering over text. The same applies to the "Signature" button in the menu bar below.

**Steps to reproduce**

1. Navigate to a live webviewer 8.3.3 instance
    + e.g. https://www.pdftron.com/webviewer/demo at time of writing
2. Click "Annotate", "Shapes", or "Redact" in the menu bar
![annotate](https://user-images.githubusercontent.com/553637/161312036-11b228a3-c082-4fe0-be45-16d3f130e336.png)
3. Click "Insert" or "Fill and Sign" in the menu bar
    + :lady_beetle: Observe that a box with "No Presets" appears, and that the Signature button in the menu bar below is not selected.
![no presets](https://user-images.githubusercontent.com/553637/161312047-4267b6e5-4d88-4613-9563-85a3dc022569.png)
4. Click "Insert" or "Fill and Sign" in the menu bar
    + Observe that the "Add New Signature" button appears in place of the "No Presets" box and that the "Signature" button in the menu bar below is selected
![add new signature](https://user-images.githubusercontent.com/553637/161312060-81af95c5-1e71-4657-8cb5-bee36ae5d47c.png)
5. Hover over some text in the document
    + :lady_beetle: Observe that the box with "No Presets" has returned, replacing the "Add New Signature" button, and that the "Signature" button in the menu bar below is deselected
![no presets](https://user-images.githubusercontent.com/553637/161312047-4267b6e5-4d88-4613-9563-85a3dc022569.png)
6. Click "Insert" or "Fill and Sign" in the menu bar
    + Observe that the "Add New Signature" button appears in place of the "No Presets" box and that the "Signature" button in the menu bar below is selected
![add new signature](https://user-images.githubusercontent.com/553637/161312060-81af95c5-1e71-4657-8cb5-bee36ae5d47c.png)

**Comment by bollain** [comment]
Hi @qguv, 

Just wanted to update that we are looking into these inconsistencies with the tool. I will provide an update when we have a fix for it.

**Comment by bollain** [comment]
@qguv we have merged a fix for this issue, and is part of or nightly stable builds for 8.4, which you can get here:
https://www.pdftron.com/nightly/#stable/

You can also install the nightly via NPM:
https://www.pdftron.com/documentation/web/faq/webviewer-nightly-build/

I will close this now but feel free to re-open if you have any further questions or issues.
