### ISSUE TITLE
[Bug] can not npm start

### ISSUE THREAD

**Issue by octopus3** [PDFTron/webviewer-ui#983]
Hi, I'm trying to `npm start` but it fail
![image](https://user-images.githubusercontent.com/26821910/175471726-6d6f838d-4de0-4f43-8990-c15fcb12636a.png)

****
step:
git clone "https://github.com/PDFTron/webviewer-ui"
npm install
npm run build
npm start
Chrome opens, and shows above error.

*****
It seems like index.html can not find webviewer-ui.min.js
![image](https://user-images.githubusercontent.com/26821910/175472091-2f0e9751-dfe3-4772-9712-a91d60bcb8cf.png)

I tried to reference webviewer-ui-min.js under the build folder,but it fail

**Comment by bollain** [comment]
Hi @octopus3

Thanks for bringing this to our attention. It seems some files meant for 8.7 accidentally made it to 8.6. I have a PR to remove these:
https://github.com/PDFTron/webviewer-ui/pull/985

When it is merged all you will need to do is pull the latest 8.6 to fix this error.

**Comment by octopus3** [comment]
OK，Thanks
