### ISSUE TITLE
[Feature Request]  Unable to show Zoom control on Web view

### ISSUE THREAD

**Issue by kevin-delong** [PDFTron/webviewer-ui#984]
**Is your feature request related to a problem? Please describe.**
I want to show Zoom In and Zoom out control on small screens. currently, this is not possible. Because we don't have any setter for the variable `hiddenOnMobileDevice` and here is the [code](https://github.com/PDFTron/webviewer-ui/blob/605ae390e7dd8506b9e4770a7bb7223c5dcf3a62/src/components/HeaderItems/HeaderItems.js#L44) which uses this variable to set CSS classes. 

if (hiddenOnMobileDevice && isMobileDeviceFunc()) {
45 | mediaQueryClassName += ' hide-in-mobile hide-in-small-mobile';

By default this variable is true.

**Comment by bollain** [comment]
Hi @kevin-delong,

Thanks for reaching out. Currently what you can do is fork the UI to change the initial state to allow the `ToggleZoomOverlay` to be shown in mobile devices. 

We have plans in an upcoming sprint to overhaul how toolbars/headers are customized, which will include options to have more granular control over mobile views.

**Comment by bollain** [comment]
You can also try this based on our existing[ header items APIs](https://www.pdftron.com/documentation/web/guides/customizing-header/)

```
  instance.UI.setHeaderItems(function(header) {
    const defaultItems = header.getHeader('default').getItems();
    const zoomOverlay = defaultItems.find(item => item.element === 'zoomOverlay');
    console.log({ zoomOverlay})
    zoomOverlay.hiddenOnMobileDevice = false;
  });
```

Viewed on an Iphone 13 pro max:
![IMG_8006203A1F41-1](https://user-images.githubusercontent.com/10825527/176062949-dd0475ce-6dd7-45d2-9620-9cadcf151260.jpeg)
