### ISSUE TITLE
[Bug] `npm start` - hot update failed for module "./src/components/App/App.js"

### ISSUE THREAD

**Issue by NyxCode** [PDFTron/webviewer-ui#986]
**WebViewer version**
8.6.1

**The current behavior**
After running `npm start`, a browser window opens, showing a blank page with this error:
```
ERROR in ./src/components/NoteTextarea/CommentTextarea/CommentTextarea.js
Module not found: Error: Can't resolve 'quill-mention' in '/home/moritz/Coding/scholarly-pdf/src/components/NoteTextarea/CommentTextarea'
ERROR in ./src/components/RedactionSearchPanel/RedactionSearchPanel.js
Module not found: Error: Can't resolve 'src/components/RedactionSearchOverlay' in '/home/moritz/Coding/scholarly-pdf/src/components/RedactionSearchPanel'
```

A popup shows

```
Hot update was not successful
(1/1)
hot update failed for module "./src/components/App/App.js". Last file processed: "./src/components/Note/Context.js".
```

**The expected behavior**
It works ^^

**Steps to reproduce**
These are the precise steps I followed:
```
git clone ..... && cd ....
npm i --legacy-peer-deps
npm run download-webviewer
npm run build
npm start
```

**Comment by NyxCode** [comment]
This issue is distinct from #980 - That only occurs when `npm run download-webviewer` is not run

**Comment by NyxCode** [comment]
I got the 8.1 and 8.2 branches working - all after that don't seem to work

**Comment by bollain** [comment]
Hi @NyxCode,

I was able to start the project from a fresh install using your steps:
![image](https://user-images.githubusercontent.com/10825527/177201755-af7667a3-4ce0-4b77-bd6c-9d5fe9e355f8.png)

Your errors point to:
1) A missing dependency, that currently is required in the [package.json](https://github.com/PDFTron/webviewer-ui/blob/8.6/package.json#L33)
2) A missing component file that currently exists in the repo [RedactionSearchOverlay](https://github.com/PDFTron/webviewer-ui/tree/8.6/src/components/RedactionOverlay)

Here somethings you could try:
- Pull latest 8.6
- Delete your node modules
- Delete the `package-lock` file

Try again to install using `npm i --legacy-peer-deps`

For reference Im using:
- Node v16.14.0
- NPM 8.3.1

**Comment by bollain** [comment]
For the second error I think it may have been due to an issue with case sensitive file paths - this can cause issues in some file systems to I have addressed it here:

https://github.com/PDFTron/webviewer-ui/pull/988
