### ISSUE TITLE
[Bug] Printing PDF with 1 page, prints 2 pages

### ISSUE THREAD

**Issue by euangordon** [PDFTron/webviewer-ui#990]
Using the latest version of 8.6.1 and also can repeat with your demo site:
https://www.pdftron.com/webviewer/demo/

Repeatable in all the main browsers: Chrome, Edge, FF, Safari.

I load up a PDF which has a single page, then print it. The PDFTron print model says there is 1 page, but once it reaches the browser print model there are 2 pages.

Example PDF
[Page 1.pdf](https://github.com/PDFTron/webviewer-ui/files/9047627/Page.1.pdf)

![image](https://user-images.githubusercontent.com/32622054/177363571-e9d835d9-8b21-4cff-a278-075a48592418.png)

![image](https://user-images.githubusercontent.com/32622054/177363662-f7ae2e75-2f2b-414a-bb71-e357c357d061.png)

**Comment by bollain** [comment]
Hi @euangordon,

I was able to reproduce this issue. Can you please submit a support request through our portal to better triage this:
https://www.pdftron.com/form/request/

**Comment by euangordon** [comment]
@bollain Submitted the request via your portal.
