### ISSUE TITLE
[Bug] Downloading Linearized Files doesn't always work in v8.6.1

### ISSUE THREAD

**Issue by euangordon** [PDFTron/webviewer-ui#991]
We are in the process of updating from WebViewer 7.2 to 8.6.1, mostly things are working, but found the streaming of linearized PDFs has stopped working.

What I see happening is that it will request the first 200 bytes of the file, which it uses work workout if the PDF is linearized, but it must decide that the file is not linearized and then tries to download the full file as it doesn't specify a byte range for the file in the second request. 

First Request:
![image](https://user-images.githubusercontent.com/32622054/177575440-37a98702-54f3-41f6-a5b9-36b04d4031c6.png)

In the Second Request, no range is specified.

With exactly the same PDF, WebViewer 7.2 does the right thing and downloads the files in chunks. However 8.6.1 doesn't.

PDF which isn't downloaded as linearized in 8.6.1, but works fine in 7.2:
[NP234Wk23-22.pdf](https://github.com/PDFTron/webviewer-ui/files/9055585/NP234Wk23-22.pdf)

One thing to add. With some PDFs it is working in both versions, but newer ones I am linearizing it isn't working

SDK Used to Linearize the PDF: v9.2.3.79556

`doc.Save(linearStream, SDFDoc.SaveOptions.e_linearized);`

Previously was using v9.0 for some time but upgraded as part of trying to diagnose this issue.

We store the PDFs in Azure Blob Storage and use a ASP.NET MVC5 API Controller to return the PDF chunks.

**Comment by bollain** [comment]
Hi @euangordon,

I see that you have submitted this as well to our support portal - thanks. This will get assigned to our team internally and you will get updates via the ticket created. I will close this issue now to keep the communication in a single channel.

**Comment by dredav** [comment]
Hi @bollain - was this an webviewer issue or an user one? I have the same issue with 8.5.0 and didn't find anything related in the changelog.

**Comment by euangordon** [comment]
@bollain okay. 

In case anyone else asks the same. The answer I received from support was that this change was deliberate change. If the file being downloaded is less size that the range, then the second API request for the file will contain no range and the full file should be returned. This is not how it worked in older versions. So example use:

1. You ask WebViewer to download a small PDF file from your API 
2. Webviewer will request the file from you API and will request the first 200 bytes of your PDF
3. You API will return those 200 bytes
4. Webviewer will see that the file is linearized but also the file size is smaller than the standard range 
5. Webviewer will request the file from the controller with no range specified
6. Your API should then return the full file.

In our case we were deliberaly rejecting calls without a range because we wanted the PDFs to only be returned if they were linearized
