### ISSUE TITLE
[Bug] Redaction panel search not working

### ISSUE THREAD

**Issue by NCuculova** [PDFTron/webviewer-ui#997]
**WebViewer version**
8.9

**The current behavior**
Search in redaction panel is not showing any results. Attached is console error.
![image](https://user-images.githubusercontent.com/4281735/197303913-6ab9a00c-07ca-417e-a7a9-317a97b407dd.png)

**The expected behavior**

**Steps to reproduce**

**Comment by bollain** [comment]
Hi @NCuculova,

Thanks for this report!

We are currently working on a fix - this will be part of our upcoming 8.10 release, but once it is done I will also backport it to 8.9. 

I'll provide an update through this issue when that is done.

**Comment by bollain** [comment]
Hi @NCuculova,

The issue has been fixed here:
https://github.com/PDFTron/webviewer-ui/commit/866c2c1eaa00bf63356b48c9815305383e1eca22

If you build the project yourself all you need to do is pull the latest 8.9 branch. If you are using our builds, simply get the latest nightly build to get the fix.
https://www.pdftron.com/documentation/web/faq/webviewer-nightly-build/#npm
